// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf type {@code pg_query.Alias}
 */
public final class Alias extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pg_query.Alias)
    AliasOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Alias.newBuilder() to construct.
  private Alias(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Alias() {
    aliasname_ = "";
    colnames_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Alias();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Alias(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            aliasname_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              colnames_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>();
              mutable_bitField0_ |= 0x00000001;
            }
            colnames_.add(
                input.readMessage(com.premiumminds.sonar.postgres.protobuf.Node.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        colnames_ = java.util.Collections.unmodifiableList(colnames_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_Alias_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_Alias_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.premiumminds.sonar.postgres.protobuf.Alias.class, com.premiumminds.sonar.postgres.protobuf.Alias.Builder.class);
  }

  public static final int ALIASNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object aliasname_;
  /**
   * <code>string aliasname = 1 [json_name = "aliasname"];</code>
   * @return The aliasname.
   */
  @java.lang.Override
  public java.lang.String getAliasname() {
    java.lang.Object ref = aliasname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      aliasname_ = s;
      return s;
    }
  }
  /**
   * <code>string aliasname = 1 [json_name = "aliasname"];</code>
   * @return The bytes for aliasname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAliasnameBytes() {
    java.lang.Object ref = aliasname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      aliasname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLNAMES_FIELD_NUMBER = 2;
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> colnames_;
  /**
   * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getColnamesList() {
    return colnames_;
  }
  /**
   * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getColnamesOrBuilderList() {
    return colnames_;
  }
  /**
   * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
   */
  @java.lang.Override
  public int getColnamesCount() {
    return colnames_.size();
  }
  /**
   * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getColnames(int index) {
    return colnames_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColnamesOrBuilder(
      int index) {
    return colnames_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(aliasname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, aliasname_);
    }
    for (int i = 0; i < colnames_.size(); i++) {
      output.writeMessage(2, colnames_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(aliasname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, aliasname_);
    }
    for (int i = 0; i < colnames_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, colnames_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.premiumminds.sonar.postgres.protobuf.Alias)) {
      return super.equals(obj);
    }
    com.premiumminds.sonar.postgres.protobuf.Alias other = (com.premiumminds.sonar.postgres.protobuf.Alias) obj;

    if (!getAliasname()
        .equals(other.getAliasname())) return false;
    if (!getColnamesList()
        .equals(other.getColnamesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALIASNAME_FIELD_NUMBER;
    hash = (53 * hash) + getAliasname().hashCode();
    if (getColnamesCount() > 0) {
      hash = (37 * hash) + COLNAMES_FIELD_NUMBER;
      hash = (53 * hash) + getColnamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.Alias parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.premiumminds.sonar.postgres.protobuf.Alias prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pg_query.Alias}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pg_query.Alias)
      com.premiumminds.sonar.postgres.protobuf.AliasOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_Alias_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_Alias_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premiumminds.sonar.postgres.protobuf.Alias.class, com.premiumminds.sonar.postgres.protobuf.Alias.Builder.class);
    }

    // Construct using com.premiumminds.sonar.postgres.protobuf.Alias.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getColnamesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      aliasname_ = "";

      if (colnamesBuilder_ == null) {
        colnames_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        colnamesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_Alias_descriptor;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.Alias getDefaultInstanceForType() {
      return com.premiumminds.sonar.postgres.protobuf.Alias.getDefaultInstance();
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.Alias build() {
      com.premiumminds.sonar.postgres.protobuf.Alias result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.Alias buildPartial() {
      com.premiumminds.sonar.postgres.protobuf.Alias result = new com.premiumminds.sonar.postgres.protobuf.Alias(this);
      int from_bitField0_ = bitField0_;
      result.aliasname_ = aliasname_;
      if (colnamesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          colnames_ = java.util.Collections.unmodifiableList(colnames_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.colnames_ = colnames_;
      } else {
        result.colnames_ = colnamesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.premiumminds.sonar.postgres.protobuf.Alias) {
        return mergeFrom((com.premiumminds.sonar.postgres.protobuf.Alias)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.premiumminds.sonar.postgres.protobuf.Alias other) {
      if (other == com.premiumminds.sonar.postgres.protobuf.Alias.getDefaultInstance()) return this;
      if (!other.getAliasname().isEmpty()) {
        aliasname_ = other.aliasname_;
        onChanged();
      }
      if (colnamesBuilder_ == null) {
        if (!other.colnames_.isEmpty()) {
          if (colnames_.isEmpty()) {
            colnames_ = other.colnames_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureColnamesIsMutable();
            colnames_.addAll(other.colnames_);
          }
          onChanged();
        }
      } else {
        if (!other.colnames_.isEmpty()) {
          if (colnamesBuilder_.isEmpty()) {
            colnamesBuilder_.dispose();
            colnamesBuilder_ = null;
            colnames_ = other.colnames_;
            bitField0_ = (bitField0_ & ~0x00000001);
            colnamesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getColnamesFieldBuilder() : null;
          } else {
            colnamesBuilder_.addAllMessages(other.colnames_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.premiumminds.sonar.postgres.protobuf.Alias parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.premiumminds.sonar.postgres.protobuf.Alias) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object aliasname_ = "";
    /**
     * <code>string aliasname = 1 [json_name = "aliasname"];</code>
     * @return The aliasname.
     */
    public java.lang.String getAliasname() {
      java.lang.Object ref = aliasname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        aliasname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string aliasname = 1 [json_name = "aliasname"];</code>
     * @return The bytes for aliasname.
     */
    public com.google.protobuf.ByteString
        getAliasnameBytes() {
      java.lang.Object ref = aliasname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aliasname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string aliasname = 1 [json_name = "aliasname"];</code>
     * @param value The aliasname to set.
     * @return This builder for chaining.
     */
    public Builder setAliasname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      aliasname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string aliasname = 1 [json_name = "aliasname"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAliasname() {
      
      aliasname_ = getDefaultInstance().getAliasname();
      onChanged();
      return this;
    }
    /**
     * <code>string aliasname = 1 [json_name = "aliasname"];</code>
     * @param value The bytes for aliasname to set.
     * @return This builder for chaining.
     */
    public Builder setAliasnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      aliasname_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> colnames_ =
      java.util.Collections.emptyList();
    private void ensureColnamesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        colnames_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(colnames_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> colnamesBuilder_;

    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getColnamesList() {
      if (colnamesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(colnames_);
      } else {
        return colnamesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public int getColnamesCount() {
      if (colnamesBuilder_ == null) {
        return colnames_.size();
      } else {
        return colnamesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getColnames(int index) {
      if (colnamesBuilder_ == null) {
        return colnames_.get(index);
      } else {
        return colnamesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder setColnames(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (colnamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColnamesIsMutable();
        colnames_.set(index, value);
        onChanged();
      } else {
        colnamesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder setColnames(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (colnamesBuilder_ == null) {
        ensureColnamesIsMutable();
        colnames_.set(index, builderForValue.build());
        onChanged();
      } else {
        colnamesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder addColnames(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (colnamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColnamesIsMutable();
        colnames_.add(value);
        onChanged();
      } else {
        colnamesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder addColnames(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (colnamesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColnamesIsMutable();
        colnames_.add(index, value);
        onChanged();
      } else {
        colnamesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder addColnames(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (colnamesBuilder_ == null) {
        ensureColnamesIsMutable();
        colnames_.add(builderForValue.build());
        onChanged();
      } else {
        colnamesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder addColnames(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (colnamesBuilder_ == null) {
        ensureColnamesIsMutable();
        colnames_.add(index, builderForValue.build());
        onChanged();
      } else {
        colnamesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder addAllColnames(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (colnamesBuilder_ == null) {
        ensureColnamesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, colnames_);
        onChanged();
      } else {
        colnamesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder clearColnames() {
      if (colnamesBuilder_ == null) {
        colnames_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        colnamesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public Builder removeColnames(int index) {
      if (colnamesBuilder_ == null) {
        ensureColnamesIsMutable();
        colnames_.remove(index);
        onChanged();
      } else {
        colnamesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getColnamesBuilder(
        int index) {
      return getColnamesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColnamesOrBuilder(
        int index) {
      if (colnamesBuilder_ == null) {
        return colnames_.get(index);  } else {
        return colnamesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getColnamesOrBuilderList() {
      if (colnamesBuilder_ != null) {
        return colnamesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(colnames_);
      }
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addColnamesBuilder() {
      return getColnamesFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addColnamesBuilder(
        int index) {
      return getColnamesFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node colnames = 2 [json_name = "colnames"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getColnamesBuilderList() {
      return getColnamesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getColnamesFieldBuilder() {
      if (colnamesBuilder_ == null) {
        colnamesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                colnames_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        colnames_ = null;
      }
      return colnamesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pg_query.Alias)
  }

  // @@protoc_insertion_point(class_scope:pg_query.Alias)
  private static final com.premiumminds.sonar.postgres.protobuf.Alias DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.premiumminds.sonar.postgres.protobuf.Alias();
  }

  public static com.premiumminds.sonar.postgres.protobuf.Alias getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Alias>
      PARSER = new com.google.protobuf.AbstractParser<Alias>() {
    @java.lang.Override
    public Alias parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Alias(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Alias> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Alias> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Alias getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

