// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

public interface CheckPointStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.CheckPointStmt)
    com.google.protobuf.MessageOrBuilder {
}
