// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf type {@code pg_query.FuncCall}
 */
public final class FuncCall extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pg_query.FuncCall)
    FuncCallOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FuncCall.newBuilder() to construct.
  private FuncCall(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FuncCall() {
    funcname_ = java.util.Collections.emptyList();
    args_ = java.util.Collections.emptyList();
    aggOrder_ = java.util.Collections.emptyList();
    funcformat_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FuncCall();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_FuncCall_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_FuncCall_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.premiumminds.sonar.postgres.protobuf.FuncCall.class, com.premiumminds.sonar.postgres.protobuf.FuncCall.Builder.class);
  }

  public static final int FUNCNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> funcname_;
  /**
   * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getFuncnameList() {
    return funcname_;
  }
  /**
   * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getFuncnameOrBuilderList() {
    return funcname_;
  }
  /**
   * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
   */
  @java.lang.Override
  public int getFuncnameCount() {
    return funcname_.size();
  }
  /**
   * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getFuncname(int index) {
    return funcname_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getFuncnameOrBuilder(
      int index) {
    return funcname_.get(index);
  }

  public static final int ARGS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> args_;
  /**
   * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getArgsList() {
    return args_;
  }
  /**
   * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getArgsOrBuilderList() {
    return args_;
  }
  /**
   * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
   */
  @java.lang.Override
  public int getArgsCount() {
    return args_.size();
  }
  /**
   * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getArgs(int index) {
    return args_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getArgsOrBuilder(
      int index) {
    return args_.get(index);
  }

  public static final int AGG_ORDER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> aggOrder_;
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getAggOrderList() {
    return aggOrder_;
  }
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getAggOrderOrBuilderList() {
    return aggOrder_;
  }
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public int getAggOrderCount() {
    return aggOrder_.size();
  }
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getAggOrder(int index) {
    return aggOrder_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getAggOrderOrBuilder(
      int index) {
    return aggOrder_.get(index);
  }

  public static final int AGG_FILTER_FIELD_NUMBER = 4;
  private com.premiumminds.sonar.postgres.protobuf.Node aggFilter_;
  /**
   * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
   * @return Whether the aggFilter field is set.
   */
  @java.lang.Override
  public boolean hasAggFilter() {
    return aggFilter_ != null;
  }
  /**
   * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
   * @return The aggFilter.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getAggFilter() {
    return aggFilter_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : aggFilter_;
  }
  /**
   * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getAggFilterOrBuilder() {
    return aggFilter_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : aggFilter_;
  }

  public static final int OVER_FIELD_NUMBER = 5;
  private com.premiumminds.sonar.postgres.protobuf.WindowDef over_;
  /**
   * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
   * @return Whether the over field is set.
   */
  @java.lang.Override
  public boolean hasOver() {
    return over_ != null;
  }
  /**
   * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
   * @return The over.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.WindowDef getOver() {
    return over_ == null ? com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance() : over_;
  }
  /**
   * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder getOverOrBuilder() {
    return over_ == null ? com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance() : over_;
  }

  public static final int AGG_WITHIN_GROUP_FIELD_NUMBER = 6;
  private boolean aggWithinGroup_ = false;
  /**
   * <code>bool agg_within_group = 6 [json_name = "agg_within_group"];</code>
   * @return The aggWithinGroup.
   */
  @java.lang.Override
  public boolean getAggWithinGroup() {
    return aggWithinGroup_;
  }

  public static final int AGG_STAR_FIELD_NUMBER = 7;
  private boolean aggStar_ = false;
  /**
   * <code>bool agg_star = 7 [json_name = "agg_star"];</code>
   * @return The aggStar.
   */
  @java.lang.Override
  public boolean getAggStar() {
    return aggStar_;
  }

  public static final int AGG_DISTINCT_FIELD_NUMBER = 8;
  private boolean aggDistinct_ = false;
  /**
   * <code>bool agg_distinct = 8 [json_name = "agg_distinct"];</code>
   * @return The aggDistinct.
   */
  @java.lang.Override
  public boolean getAggDistinct() {
    return aggDistinct_;
  }

  public static final int FUNC_VARIADIC_FIELD_NUMBER = 9;
  private boolean funcVariadic_ = false;
  /**
   * <code>bool func_variadic = 9 [json_name = "func_variadic"];</code>
   * @return The funcVariadic.
   */
  @java.lang.Override
  public boolean getFuncVariadic() {
    return funcVariadic_;
  }

  public static final int FUNCFORMAT_FIELD_NUMBER = 10;
  private int funcformat_ = 0;
  /**
   * <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
   * @return The enum numeric value on the wire for funcformat.
   */
  @java.lang.Override public int getFuncformatValue() {
    return funcformat_;
  }
  /**
   * <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
   * @return The funcformat.
   */
  @java.lang.Override public com.premiumminds.sonar.postgres.protobuf.CoercionForm getFuncformat() {
    com.premiumminds.sonar.postgres.protobuf.CoercionForm result = com.premiumminds.sonar.postgres.protobuf.CoercionForm.forNumber(funcformat_);
    return result == null ? com.premiumminds.sonar.postgres.protobuf.CoercionForm.UNRECOGNIZED : result;
  }

  public static final int LOCATION_FIELD_NUMBER = 11;
  private int location_ = 0;
  /**
   * <code>int32 location = 11 [json_name = "location"];</code>
   * @return The location.
   */
  @java.lang.Override
  public int getLocation() {
    return location_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < funcname_.size(); i++) {
      output.writeMessage(1, funcname_.get(i));
    }
    for (int i = 0; i < args_.size(); i++) {
      output.writeMessage(2, args_.get(i));
    }
    for (int i = 0; i < aggOrder_.size(); i++) {
      output.writeMessage(3, aggOrder_.get(i));
    }
    if (aggFilter_ != null) {
      output.writeMessage(4, getAggFilter());
    }
    if (over_ != null) {
      output.writeMessage(5, getOver());
    }
    if (aggWithinGroup_ != false) {
      output.writeBool(6, aggWithinGroup_);
    }
    if (aggStar_ != false) {
      output.writeBool(7, aggStar_);
    }
    if (aggDistinct_ != false) {
      output.writeBool(8, aggDistinct_);
    }
    if (funcVariadic_ != false) {
      output.writeBool(9, funcVariadic_);
    }
    if (funcformat_ != com.premiumminds.sonar.postgres.protobuf.CoercionForm.COERCION_FORM_UNDEFINED.getNumber()) {
      output.writeEnum(10, funcformat_);
    }
    if (location_ != 0) {
      output.writeInt32(11, location_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < funcname_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, funcname_.get(i));
    }
    for (int i = 0; i < args_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, args_.get(i));
    }
    for (int i = 0; i < aggOrder_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, aggOrder_.get(i));
    }
    if (aggFilter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAggFilter());
    }
    if (over_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getOver());
    }
    if (aggWithinGroup_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, aggWithinGroup_);
    }
    if (aggStar_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, aggStar_);
    }
    if (aggDistinct_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, aggDistinct_);
    }
    if (funcVariadic_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(9, funcVariadic_);
    }
    if (funcformat_ != com.premiumminds.sonar.postgres.protobuf.CoercionForm.COERCION_FORM_UNDEFINED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(10, funcformat_);
    }
    if (location_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, location_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.premiumminds.sonar.postgres.protobuf.FuncCall)) {
      return super.equals(obj);
    }
    com.premiumminds.sonar.postgres.protobuf.FuncCall other = (com.premiumminds.sonar.postgres.protobuf.FuncCall) obj;

    if (!getFuncnameList()
        .equals(other.getFuncnameList())) return false;
    if (!getArgsList()
        .equals(other.getArgsList())) return false;
    if (!getAggOrderList()
        .equals(other.getAggOrderList())) return false;
    if (hasAggFilter() != other.hasAggFilter()) return false;
    if (hasAggFilter()) {
      if (!getAggFilter()
          .equals(other.getAggFilter())) return false;
    }
    if (hasOver() != other.hasOver()) return false;
    if (hasOver()) {
      if (!getOver()
          .equals(other.getOver())) return false;
    }
    if (getAggWithinGroup()
        != other.getAggWithinGroup()) return false;
    if (getAggStar()
        != other.getAggStar()) return false;
    if (getAggDistinct()
        != other.getAggDistinct()) return false;
    if (getFuncVariadic()
        != other.getFuncVariadic()) return false;
    if (funcformat_ != other.funcformat_) return false;
    if (getLocation()
        != other.getLocation()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getFuncnameCount() > 0) {
      hash = (37 * hash) + FUNCNAME_FIELD_NUMBER;
      hash = (53 * hash) + getFuncnameList().hashCode();
    }
    if (getArgsCount() > 0) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgsList().hashCode();
    }
    if (getAggOrderCount() > 0) {
      hash = (37 * hash) + AGG_ORDER_FIELD_NUMBER;
      hash = (53 * hash) + getAggOrderList().hashCode();
    }
    if (hasAggFilter()) {
      hash = (37 * hash) + AGG_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getAggFilter().hashCode();
    }
    if (hasOver()) {
      hash = (37 * hash) + OVER_FIELD_NUMBER;
      hash = (53 * hash) + getOver().hashCode();
    }
    hash = (37 * hash) + AGG_WITHIN_GROUP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAggWithinGroup());
    hash = (37 * hash) + AGG_STAR_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAggStar());
    hash = (37 * hash) + AGG_DISTINCT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAggDistinct());
    hash = (37 * hash) + FUNC_VARIADIC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFuncVariadic());
    hash = (37 * hash) + FUNCFORMAT_FIELD_NUMBER;
    hash = (53 * hash) + funcformat_;
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.FuncCall parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.premiumminds.sonar.postgres.protobuf.FuncCall prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pg_query.FuncCall}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pg_query.FuncCall)
      com.premiumminds.sonar.postgres.protobuf.FuncCallOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_FuncCall_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_FuncCall_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premiumminds.sonar.postgres.protobuf.FuncCall.class, com.premiumminds.sonar.postgres.protobuf.FuncCall.Builder.class);
    }

    // Construct using com.premiumminds.sonar.postgres.protobuf.FuncCall.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (funcnameBuilder_ == null) {
        funcname_ = java.util.Collections.emptyList();
      } else {
        funcname_ = null;
        funcnameBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (argsBuilder_ == null) {
        args_ = java.util.Collections.emptyList();
      } else {
        args_ = null;
        argsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (aggOrderBuilder_ == null) {
        aggOrder_ = java.util.Collections.emptyList();
      } else {
        aggOrder_ = null;
        aggOrderBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      aggFilter_ = null;
      if (aggFilterBuilder_ != null) {
        aggFilterBuilder_.dispose();
        aggFilterBuilder_ = null;
      }
      over_ = null;
      if (overBuilder_ != null) {
        overBuilder_.dispose();
        overBuilder_ = null;
      }
      aggWithinGroup_ = false;
      aggStar_ = false;
      aggDistinct_ = false;
      funcVariadic_ = false;
      funcformat_ = 0;
      location_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_FuncCall_descriptor;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.FuncCall getDefaultInstanceForType() {
      return com.premiumminds.sonar.postgres.protobuf.FuncCall.getDefaultInstance();
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.FuncCall build() {
      com.premiumminds.sonar.postgres.protobuf.FuncCall result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.FuncCall buildPartial() {
      com.premiumminds.sonar.postgres.protobuf.FuncCall result = new com.premiumminds.sonar.postgres.protobuf.FuncCall(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.premiumminds.sonar.postgres.protobuf.FuncCall result) {
      if (funcnameBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          funcname_ = java.util.Collections.unmodifiableList(funcname_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.funcname_ = funcname_;
      } else {
        result.funcname_ = funcnameBuilder_.build();
      }
      if (argsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          args_ = java.util.Collections.unmodifiableList(args_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.args_ = args_;
      } else {
        result.args_ = argsBuilder_.build();
      }
      if (aggOrderBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          aggOrder_ = java.util.Collections.unmodifiableList(aggOrder_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.aggOrder_ = aggOrder_;
      } else {
        result.aggOrder_ = aggOrderBuilder_.build();
      }
    }

    private void buildPartial0(com.premiumminds.sonar.postgres.protobuf.FuncCall result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.aggFilter_ = aggFilterBuilder_ == null
            ? aggFilter_
            : aggFilterBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.over_ = overBuilder_ == null
            ? over_
            : overBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.aggWithinGroup_ = aggWithinGroup_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.aggStar_ = aggStar_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.aggDistinct_ = aggDistinct_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.funcVariadic_ = funcVariadic_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.funcformat_ = funcformat_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.location_ = location_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.premiumminds.sonar.postgres.protobuf.FuncCall) {
        return mergeFrom((com.premiumminds.sonar.postgres.protobuf.FuncCall)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.premiumminds.sonar.postgres.protobuf.FuncCall other) {
      if (other == com.premiumminds.sonar.postgres.protobuf.FuncCall.getDefaultInstance()) return this;
      if (funcnameBuilder_ == null) {
        if (!other.funcname_.isEmpty()) {
          if (funcname_.isEmpty()) {
            funcname_ = other.funcname_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFuncnameIsMutable();
            funcname_.addAll(other.funcname_);
          }
          onChanged();
        }
      } else {
        if (!other.funcname_.isEmpty()) {
          if (funcnameBuilder_.isEmpty()) {
            funcnameBuilder_.dispose();
            funcnameBuilder_ = null;
            funcname_ = other.funcname_;
            bitField0_ = (bitField0_ & ~0x00000001);
            funcnameBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFuncnameFieldBuilder() : null;
          } else {
            funcnameBuilder_.addAllMessages(other.funcname_);
          }
        }
      }
      if (argsBuilder_ == null) {
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
      } else {
        if (!other.args_.isEmpty()) {
          if (argsBuilder_.isEmpty()) {
            argsBuilder_.dispose();
            argsBuilder_ = null;
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000002);
            argsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getArgsFieldBuilder() : null;
          } else {
            argsBuilder_.addAllMessages(other.args_);
          }
        }
      }
      if (aggOrderBuilder_ == null) {
        if (!other.aggOrder_.isEmpty()) {
          if (aggOrder_.isEmpty()) {
            aggOrder_ = other.aggOrder_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAggOrderIsMutable();
            aggOrder_.addAll(other.aggOrder_);
          }
          onChanged();
        }
      } else {
        if (!other.aggOrder_.isEmpty()) {
          if (aggOrderBuilder_.isEmpty()) {
            aggOrderBuilder_.dispose();
            aggOrderBuilder_ = null;
            aggOrder_ = other.aggOrder_;
            bitField0_ = (bitField0_ & ~0x00000004);
            aggOrderBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAggOrderFieldBuilder() : null;
          } else {
            aggOrderBuilder_.addAllMessages(other.aggOrder_);
          }
        }
      }
      if (other.hasAggFilter()) {
        mergeAggFilter(other.getAggFilter());
      }
      if (other.hasOver()) {
        mergeOver(other.getOver());
      }
      if (other.getAggWithinGroup() != false) {
        setAggWithinGroup(other.getAggWithinGroup());
      }
      if (other.getAggStar() != false) {
        setAggStar(other.getAggStar());
      }
      if (other.getAggDistinct() != false) {
        setAggDistinct(other.getAggDistinct());
      }
      if (other.getFuncVariadic() != false) {
        setFuncVariadic(other.getFuncVariadic());
      }
      if (other.funcformat_ != 0) {
        setFuncformatValue(other.getFuncformatValue());
      }
      if (other.getLocation() != 0) {
        setLocation(other.getLocation());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (funcnameBuilder_ == null) {
                ensureFuncnameIsMutable();
                funcname_.add(m);
              } else {
                funcnameBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (argsBuilder_ == null) {
                ensureArgsIsMutable();
                args_.add(m);
              } else {
                argsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (aggOrderBuilder_ == null) {
                ensureAggOrderIsMutable();
                aggOrder_.add(m);
              } else {
                aggOrderBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getAggFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getOverFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              aggWithinGroup_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              aggStar_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              aggDistinct_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              funcVariadic_ = input.readBool();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              funcformat_ = input.readEnum();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              location_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> funcname_ =
      java.util.Collections.emptyList();
    private void ensureFuncnameIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        funcname_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(funcname_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> funcnameBuilder_;

    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getFuncnameList() {
      if (funcnameBuilder_ == null) {
        return java.util.Collections.unmodifiableList(funcname_);
      } else {
        return funcnameBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public int getFuncnameCount() {
      if (funcnameBuilder_ == null) {
        return funcname_.size();
      } else {
        return funcnameBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getFuncname(int index) {
      if (funcnameBuilder_ == null) {
        return funcname_.get(index);
      } else {
        return funcnameBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder setFuncname(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (funcnameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFuncnameIsMutable();
        funcname_.set(index, value);
        onChanged();
      } else {
        funcnameBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder setFuncname(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (funcnameBuilder_ == null) {
        ensureFuncnameIsMutable();
        funcname_.set(index, builderForValue.build());
        onChanged();
      } else {
        funcnameBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder addFuncname(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (funcnameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFuncnameIsMutable();
        funcname_.add(value);
        onChanged();
      } else {
        funcnameBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder addFuncname(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (funcnameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFuncnameIsMutable();
        funcname_.add(index, value);
        onChanged();
      } else {
        funcnameBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder addFuncname(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (funcnameBuilder_ == null) {
        ensureFuncnameIsMutable();
        funcname_.add(builderForValue.build());
        onChanged();
      } else {
        funcnameBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder addFuncname(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (funcnameBuilder_ == null) {
        ensureFuncnameIsMutable();
        funcname_.add(index, builderForValue.build());
        onChanged();
      } else {
        funcnameBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder addAllFuncname(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (funcnameBuilder_ == null) {
        ensureFuncnameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, funcname_);
        onChanged();
      } else {
        funcnameBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder clearFuncname() {
      if (funcnameBuilder_ == null) {
        funcname_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        funcnameBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public Builder removeFuncname(int index) {
      if (funcnameBuilder_ == null) {
        ensureFuncnameIsMutable();
        funcname_.remove(index);
        onChanged();
      } else {
        funcnameBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getFuncnameBuilder(
        int index) {
      return getFuncnameFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getFuncnameOrBuilder(
        int index) {
      if (funcnameBuilder_ == null) {
        return funcname_.get(index);  } else {
        return funcnameBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getFuncnameOrBuilderList() {
      if (funcnameBuilder_ != null) {
        return funcnameBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(funcname_);
      }
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addFuncnameBuilder() {
      return getFuncnameFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addFuncnameBuilder(
        int index) {
      return getFuncnameFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node funcname = 1 [json_name = "funcname"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getFuncnameBuilderList() {
      return getFuncnameFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getFuncnameFieldBuilder() {
      if (funcnameBuilder_ == null) {
        funcnameBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                funcname_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        funcname_ = null;
      }
      return funcnameBuilder_;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> args_ =
      java.util.Collections.emptyList();
    private void ensureArgsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        args_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(args_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> argsBuilder_;

    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getArgsList() {
      if (argsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(args_);
      } else {
        return argsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public int getArgsCount() {
      if (argsBuilder_ == null) {
        return args_.size();
      } else {
        return argsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getArgs(int index) {
      if (argsBuilder_ == null) {
        return args_.get(index);
      } else {
        return argsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder setArgs(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.set(index, value);
        onChanged();
      } else {
        argsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder setArgs(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.set(index, builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder addArgs(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.add(value);
        onChanged();
      } else {
        argsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder addArgs(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (argsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureArgsIsMutable();
        args_.add(index, value);
        onChanged();
      } else {
        argsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder addArgs(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.add(builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder addArgs(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.add(index, builderForValue.build());
        onChanged();
      } else {
        argsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder addAllArgs(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
      } else {
        argsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder clearArgs() {
      if (argsBuilder_ == null) {
        args_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        argsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public Builder removeArgs(int index) {
      if (argsBuilder_ == null) {
        ensureArgsIsMutable();
        args_.remove(index);
        onChanged();
      } else {
        argsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getArgsBuilder(
        int index) {
      return getArgsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getArgsOrBuilder(
        int index) {
      if (argsBuilder_ == null) {
        return args_.get(index);  } else {
        return argsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getArgsOrBuilderList() {
      if (argsBuilder_ != null) {
        return argsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(args_);
      }
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addArgsBuilder() {
      return getArgsFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addArgsBuilder(
        int index) {
      return getArgsFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node args = 2 [json_name = "args"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getArgsBuilderList() {
      return getArgsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getArgsFieldBuilder() {
      if (argsBuilder_ == null) {
        argsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                args_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        args_ = null;
      }
      return argsBuilder_;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> aggOrder_ =
      java.util.Collections.emptyList();
    private void ensureAggOrderIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        aggOrder_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(aggOrder_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> aggOrderBuilder_;

    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getAggOrderList() {
      if (aggOrderBuilder_ == null) {
        return java.util.Collections.unmodifiableList(aggOrder_);
      } else {
        return aggOrderBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public int getAggOrderCount() {
      if (aggOrderBuilder_ == null) {
        return aggOrder_.size();
      } else {
        return aggOrderBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getAggOrder(int index) {
      if (aggOrderBuilder_ == null) {
        return aggOrder_.get(index);
      } else {
        return aggOrderBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder setAggOrder(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggOrderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAggOrderIsMutable();
        aggOrder_.set(index, value);
        onChanged();
      } else {
        aggOrderBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder setAggOrder(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        aggOrder_.set(index, builderForValue.build());
        onChanged();
      } else {
        aggOrderBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAggOrder(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggOrderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAggOrderIsMutable();
        aggOrder_.add(value);
        onChanged();
      } else {
        aggOrderBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAggOrder(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggOrderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAggOrderIsMutable();
        aggOrder_.add(index, value);
        onChanged();
      } else {
        aggOrderBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAggOrder(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        aggOrder_.add(builderForValue.build());
        onChanged();
      } else {
        aggOrderBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAggOrder(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        aggOrder_.add(index, builderForValue.build());
        onChanged();
      } else {
        aggOrderBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAllAggOrder(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aggOrder_);
        onChanged();
      } else {
        aggOrderBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder clearAggOrder() {
      if (aggOrderBuilder_ == null) {
        aggOrder_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        aggOrderBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder removeAggOrder(int index) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        aggOrder_.remove(index);
        onChanged();
      } else {
        aggOrderBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getAggOrderBuilder(
        int index) {
      return getAggOrderFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getAggOrderOrBuilder(
        int index) {
      if (aggOrderBuilder_ == null) {
        return aggOrder_.get(index);  } else {
        return aggOrderBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getAggOrderOrBuilderList() {
      if (aggOrderBuilder_ != null) {
        return aggOrderBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(aggOrder_);
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addAggOrderBuilder() {
      return getAggOrderFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addAggOrderBuilder(
        int index) {
      return getAggOrderFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getAggOrderBuilderList() {
      return getAggOrderFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getAggOrderFieldBuilder() {
      if (aggOrderBuilder_ == null) {
        aggOrderBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                aggOrder_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        aggOrder_ = null;
      }
      return aggOrderBuilder_;
    }

    private com.premiumminds.sonar.postgres.protobuf.Node aggFilter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> aggFilterBuilder_;
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     * @return Whether the aggFilter field is set.
     */
    public boolean hasAggFilter() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     * @return The aggFilter.
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getAggFilter() {
      if (aggFilterBuilder_ == null) {
        return aggFilter_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : aggFilter_;
      } else {
        return aggFilterBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     */
    public Builder setAggFilter(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggFilterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aggFilter_ = value;
      } else {
        aggFilterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     */
    public Builder setAggFilter(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (aggFilterBuilder_ == null) {
        aggFilter_ = builderForValue.build();
      } else {
        aggFilterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     */
    public Builder mergeAggFilter(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggFilterBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          aggFilter_ != null &&
          aggFilter_ != com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance()) {
          getAggFilterBuilder().mergeFrom(value);
        } else {
          aggFilter_ = value;
        }
      } else {
        aggFilterBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     */
    public Builder clearAggFilter() {
      bitField0_ = (bitField0_ & ~0x00000008);
      aggFilter_ = null;
      if (aggFilterBuilder_ != null) {
        aggFilterBuilder_.dispose();
        aggFilterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getAggFilterBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getAggFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getAggFilterOrBuilder() {
      if (aggFilterBuilder_ != null) {
        return aggFilterBuilder_.getMessageOrBuilder();
      } else {
        return aggFilter_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : aggFilter_;
      }
    }
    /**
     * <code>.pg_query.Node agg_filter = 4 [json_name = "agg_filter"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getAggFilterFieldBuilder() {
      if (aggFilterBuilder_ == null) {
        aggFilterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                getAggFilter(),
                getParentForChildren(),
                isClean());
        aggFilter_ = null;
      }
      return aggFilterBuilder_;
    }

    private com.premiumminds.sonar.postgres.protobuf.WindowDef over_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.WindowDef, com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder, com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder> overBuilder_;
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     * @return Whether the over field is set.
     */
    public boolean hasOver() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     * @return The over.
     */
    public com.premiumminds.sonar.postgres.protobuf.WindowDef getOver() {
      if (overBuilder_ == null) {
        return over_ == null ? com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance() : over_;
      } else {
        return overBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     */
    public Builder setOver(com.premiumminds.sonar.postgres.protobuf.WindowDef value) {
      if (overBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        over_ = value;
      } else {
        overBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     */
    public Builder setOver(
        com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder builderForValue) {
      if (overBuilder_ == null) {
        over_ = builderForValue.build();
      } else {
        overBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     */
    public Builder mergeOver(com.premiumminds.sonar.postgres.protobuf.WindowDef value) {
      if (overBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          over_ != null &&
          over_ != com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance()) {
          getOverBuilder().mergeFrom(value);
        } else {
          over_ = value;
        }
      } else {
        overBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     */
    public Builder clearOver() {
      bitField0_ = (bitField0_ & ~0x00000010);
      over_ = null;
      if (overBuilder_ != null) {
        overBuilder_.dispose();
        overBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder getOverBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getOverFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder getOverOrBuilder() {
      if (overBuilder_ != null) {
        return overBuilder_.getMessageOrBuilder();
      } else {
        return over_ == null ?
            com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance() : over_;
      }
    }
    /**
     * <code>.pg_query.WindowDef over = 5 [json_name = "over"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.WindowDef, com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder, com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder> 
        getOverFieldBuilder() {
      if (overBuilder_ == null) {
        overBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.WindowDef, com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder, com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder>(
                getOver(),
                getParentForChildren(),
                isClean());
        over_ = null;
      }
      return overBuilder_;
    }

    private boolean aggWithinGroup_ ;
    /**
     * <code>bool agg_within_group = 6 [json_name = "agg_within_group"];</code>
     * @return The aggWithinGroup.
     */
    @java.lang.Override
    public boolean getAggWithinGroup() {
      return aggWithinGroup_;
    }
    /**
     * <code>bool agg_within_group = 6 [json_name = "agg_within_group"];</code>
     * @param value The aggWithinGroup to set.
     * @return This builder for chaining.
     */
    public Builder setAggWithinGroup(boolean value) {
      
      aggWithinGroup_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool agg_within_group = 6 [json_name = "agg_within_group"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAggWithinGroup() {
      bitField0_ = (bitField0_ & ~0x00000020);
      aggWithinGroup_ = false;
      onChanged();
      return this;
    }

    private boolean aggStar_ ;
    /**
     * <code>bool agg_star = 7 [json_name = "agg_star"];</code>
     * @return The aggStar.
     */
    @java.lang.Override
    public boolean getAggStar() {
      return aggStar_;
    }
    /**
     * <code>bool agg_star = 7 [json_name = "agg_star"];</code>
     * @param value The aggStar to set.
     * @return This builder for chaining.
     */
    public Builder setAggStar(boolean value) {
      
      aggStar_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool agg_star = 7 [json_name = "agg_star"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAggStar() {
      bitField0_ = (bitField0_ & ~0x00000040);
      aggStar_ = false;
      onChanged();
      return this;
    }

    private boolean aggDistinct_ ;
    /**
     * <code>bool agg_distinct = 8 [json_name = "agg_distinct"];</code>
     * @return The aggDistinct.
     */
    @java.lang.Override
    public boolean getAggDistinct() {
      return aggDistinct_;
    }
    /**
     * <code>bool agg_distinct = 8 [json_name = "agg_distinct"];</code>
     * @param value The aggDistinct to set.
     * @return This builder for chaining.
     */
    public Builder setAggDistinct(boolean value) {
      
      aggDistinct_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool agg_distinct = 8 [json_name = "agg_distinct"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAggDistinct() {
      bitField0_ = (bitField0_ & ~0x00000080);
      aggDistinct_ = false;
      onChanged();
      return this;
    }

    private boolean funcVariadic_ ;
    /**
     * <code>bool func_variadic = 9 [json_name = "func_variadic"];</code>
     * @return The funcVariadic.
     */
    @java.lang.Override
    public boolean getFuncVariadic() {
      return funcVariadic_;
    }
    /**
     * <code>bool func_variadic = 9 [json_name = "func_variadic"];</code>
     * @param value The funcVariadic to set.
     * @return This builder for chaining.
     */
    public Builder setFuncVariadic(boolean value) {
      
      funcVariadic_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>bool func_variadic = 9 [json_name = "func_variadic"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFuncVariadic() {
      bitField0_ = (bitField0_ & ~0x00000100);
      funcVariadic_ = false;
      onChanged();
      return this;
    }

    private int funcformat_ = 0;
    /**
     * <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
     * @return The enum numeric value on the wire for funcformat.
     */
    @java.lang.Override public int getFuncformatValue() {
      return funcformat_;
    }
    /**
     * <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
     * @param value The enum numeric value on the wire for funcformat to set.
     * @return This builder for chaining.
     */
    public Builder setFuncformatValue(int value) {
      funcformat_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
     * @return The funcformat.
     */
    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.CoercionForm getFuncformat() {
      com.premiumminds.sonar.postgres.protobuf.CoercionForm result = com.premiumminds.sonar.postgres.protobuf.CoercionForm.forNumber(funcformat_);
      return result == null ? com.premiumminds.sonar.postgres.protobuf.CoercionForm.UNRECOGNIZED : result;
    }
    /**
     * <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
     * @param value The funcformat to set.
     * @return This builder for chaining.
     */
    public Builder setFuncformat(com.premiumminds.sonar.postgres.protobuf.CoercionForm value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000200;
      funcformat_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.CoercionForm funcformat = 10 [json_name = "funcformat"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFuncformat() {
      bitField0_ = (bitField0_ & ~0x00000200);
      funcformat_ = 0;
      onChanged();
      return this;
    }

    private int location_ ;
    /**
     * <code>int32 location = 11 [json_name = "location"];</code>
     * @return The location.
     */
    @java.lang.Override
    public int getLocation() {
      return location_;
    }
    /**
     * <code>int32 location = 11 [json_name = "location"];</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(int value) {
      
      location_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 location = 11 [json_name = "location"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      bitField0_ = (bitField0_ & ~0x00000400);
      location_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pg_query.FuncCall)
  }

  // @@protoc_insertion_point(class_scope:pg_query.FuncCall)
  private static final com.premiumminds.sonar.postgres.protobuf.FuncCall DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.premiumminds.sonar.postgres.protobuf.FuncCall();
  }

  public static com.premiumminds.sonar.postgres.protobuf.FuncCall getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FuncCall>
      PARSER = new com.google.protobuf.AbstractParser<FuncCall>() {
    @java.lang.Override
    public FuncCall parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FuncCall> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FuncCall> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.FuncCall getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

