// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf type {@code pg_query.JsonAggConstructor}
 */
public final class JsonAggConstructor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pg_query.JsonAggConstructor)
    JsonAggConstructorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JsonAggConstructor.newBuilder() to construct.
  private JsonAggConstructor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JsonAggConstructor() {
    aggOrder_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JsonAggConstructor();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_JsonAggConstructor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_JsonAggConstructor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor.class, com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor.Builder.class);
  }

  public static final int OUTPUT_FIELD_NUMBER = 1;
  private com.premiumminds.sonar.postgres.protobuf.JsonOutput output_;
  /**
   * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
   * @return Whether the output field is set.
   */
  @java.lang.Override
  public boolean hasOutput() {
    return output_ != null;
  }
  /**
   * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
   * @return The output.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.JsonOutput getOutput() {
    return output_ == null ? com.premiumminds.sonar.postgres.protobuf.JsonOutput.getDefaultInstance() : output_;
  }
  /**
   * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.JsonOutputOrBuilder getOutputOrBuilder() {
    return output_ == null ? com.premiumminds.sonar.postgres.protobuf.JsonOutput.getDefaultInstance() : output_;
  }

  public static final int AGG_FILTER_FIELD_NUMBER = 2;
  private com.premiumminds.sonar.postgres.protobuf.Node aggFilter_;
  /**
   * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
   * @return Whether the aggFilter field is set.
   */
  @java.lang.Override
  public boolean hasAggFilter() {
    return aggFilter_ != null;
  }
  /**
   * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
   * @return The aggFilter.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getAggFilter() {
    return aggFilter_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : aggFilter_;
  }
  /**
   * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getAggFilterOrBuilder() {
    return aggFilter_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : aggFilter_;
  }

  public static final int AGG_ORDER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> aggOrder_;
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getAggOrderList() {
    return aggOrder_;
  }
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getAggOrderOrBuilderList() {
    return aggOrder_;
  }
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public int getAggOrderCount() {
    return aggOrder_.size();
  }
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getAggOrder(int index) {
    return aggOrder_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getAggOrderOrBuilder(
      int index) {
    return aggOrder_.get(index);
  }

  public static final int OVER_FIELD_NUMBER = 4;
  private com.premiumminds.sonar.postgres.protobuf.WindowDef over_;
  /**
   * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
   * @return Whether the over field is set.
   */
  @java.lang.Override
  public boolean hasOver() {
    return over_ != null;
  }
  /**
   * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
   * @return The over.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.WindowDef getOver() {
    return over_ == null ? com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance() : over_;
  }
  /**
   * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder getOverOrBuilder() {
    return over_ == null ? com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance() : over_;
  }

  public static final int LOCATION_FIELD_NUMBER = 5;
  private int location_ = 0;
  /**
   * <code>int32 location = 5 [json_name = "location"];</code>
   * @return The location.
   */
  @java.lang.Override
  public int getLocation() {
    return location_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (output_ != null) {
      output.writeMessage(1, getOutput());
    }
    if (aggFilter_ != null) {
      output.writeMessage(2, getAggFilter());
    }
    for (int i = 0; i < aggOrder_.size(); i++) {
      output.writeMessage(3, aggOrder_.get(i));
    }
    if (over_ != null) {
      output.writeMessage(4, getOver());
    }
    if (location_ != 0) {
      output.writeInt32(5, location_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (output_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOutput());
    }
    if (aggFilter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAggFilter());
    }
    for (int i = 0; i < aggOrder_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, aggOrder_.get(i));
    }
    if (over_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOver());
    }
    if (location_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, location_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor)) {
      return super.equals(obj);
    }
    com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor other = (com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor) obj;

    if (hasOutput() != other.hasOutput()) return false;
    if (hasOutput()) {
      if (!getOutput()
          .equals(other.getOutput())) return false;
    }
    if (hasAggFilter() != other.hasAggFilter()) return false;
    if (hasAggFilter()) {
      if (!getAggFilter()
          .equals(other.getAggFilter())) return false;
    }
    if (!getAggOrderList()
        .equals(other.getAggOrderList())) return false;
    if (hasOver() != other.hasOver()) return false;
    if (hasOver()) {
      if (!getOver()
          .equals(other.getOver())) return false;
    }
    if (getLocation()
        != other.getLocation()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOutput()) {
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
    }
    if (hasAggFilter()) {
      hash = (37 * hash) + AGG_FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getAggFilter().hashCode();
    }
    if (getAggOrderCount() > 0) {
      hash = (37 * hash) + AGG_ORDER_FIELD_NUMBER;
      hash = (53 * hash) + getAggOrderList().hashCode();
    }
    if (hasOver()) {
      hash = (37 * hash) + OVER_FIELD_NUMBER;
      hash = (53 * hash) + getOver().hashCode();
    }
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pg_query.JsonAggConstructor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pg_query.JsonAggConstructor)
      com.premiumminds.sonar.postgres.protobuf.JsonAggConstructorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_JsonAggConstructor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_JsonAggConstructor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor.class, com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor.Builder.class);
    }

    // Construct using com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      output_ = null;
      if (outputBuilder_ != null) {
        outputBuilder_.dispose();
        outputBuilder_ = null;
      }
      aggFilter_ = null;
      if (aggFilterBuilder_ != null) {
        aggFilterBuilder_.dispose();
        aggFilterBuilder_ = null;
      }
      if (aggOrderBuilder_ == null) {
        aggOrder_ = java.util.Collections.emptyList();
      } else {
        aggOrder_ = null;
        aggOrderBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      over_ = null;
      if (overBuilder_ != null) {
        overBuilder_.dispose();
        overBuilder_ = null;
      }
      location_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_JsonAggConstructor_descriptor;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor getDefaultInstanceForType() {
      return com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor.getDefaultInstance();
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor build() {
      com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor buildPartial() {
      com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor result = new com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor result) {
      if (aggOrderBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          aggOrder_ = java.util.Collections.unmodifiableList(aggOrder_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.aggOrder_ = aggOrder_;
      } else {
        result.aggOrder_ = aggOrderBuilder_.build();
      }
    }

    private void buildPartial0(com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.output_ = outputBuilder_ == null
            ? output_
            : outputBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.aggFilter_ = aggFilterBuilder_ == null
            ? aggFilter_
            : aggFilterBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.over_ = overBuilder_ == null
            ? over_
            : overBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.location_ = location_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor) {
        return mergeFrom((com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor other) {
      if (other == com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor.getDefaultInstance()) return this;
      if (other.hasOutput()) {
        mergeOutput(other.getOutput());
      }
      if (other.hasAggFilter()) {
        mergeAggFilter(other.getAggFilter());
      }
      if (aggOrderBuilder_ == null) {
        if (!other.aggOrder_.isEmpty()) {
          if (aggOrder_.isEmpty()) {
            aggOrder_ = other.aggOrder_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureAggOrderIsMutable();
            aggOrder_.addAll(other.aggOrder_);
          }
          onChanged();
        }
      } else {
        if (!other.aggOrder_.isEmpty()) {
          if (aggOrderBuilder_.isEmpty()) {
            aggOrderBuilder_.dispose();
            aggOrderBuilder_ = null;
            aggOrder_ = other.aggOrder_;
            bitField0_ = (bitField0_ & ~0x00000004);
            aggOrderBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAggOrderFieldBuilder() : null;
          } else {
            aggOrderBuilder_.addAllMessages(other.aggOrder_);
          }
        }
      }
      if (other.hasOver()) {
        mergeOver(other.getOver());
      }
      if (other.getLocation() != 0) {
        setLocation(other.getLocation());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getOutputFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getAggFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (aggOrderBuilder_ == null) {
                ensureAggOrderIsMutable();
                aggOrder_.add(m);
              } else {
                aggOrderBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getOverFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              location_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.premiumminds.sonar.postgres.protobuf.JsonOutput output_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.JsonOutput, com.premiumminds.sonar.postgres.protobuf.JsonOutput.Builder, com.premiumminds.sonar.postgres.protobuf.JsonOutputOrBuilder> outputBuilder_;
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     * @return Whether the output field is set.
     */
    public boolean hasOutput() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     * @return The output.
     */
    public com.premiumminds.sonar.postgres.protobuf.JsonOutput getOutput() {
      if (outputBuilder_ == null) {
        return output_ == null ? com.premiumminds.sonar.postgres.protobuf.JsonOutput.getDefaultInstance() : output_;
      } else {
        return outputBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     */
    public Builder setOutput(com.premiumminds.sonar.postgres.protobuf.JsonOutput value) {
      if (outputBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        output_ = value;
      } else {
        outputBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     */
    public Builder setOutput(
        com.premiumminds.sonar.postgres.protobuf.JsonOutput.Builder builderForValue) {
      if (outputBuilder_ == null) {
        output_ = builderForValue.build();
      } else {
        outputBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     */
    public Builder mergeOutput(com.premiumminds.sonar.postgres.protobuf.JsonOutput value) {
      if (outputBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          output_ != null &&
          output_ != com.premiumminds.sonar.postgres.protobuf.JsonOutput.getDefaultInstance()) {
          getOutputBuilder().mergeFrom(value);
        } else {
          output_ = value;
        }
      } else {
        outputBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     */
    public Builder clearOutput() {
      bitField0_ = (bitField0_ & ~0x00000001);
      output_ = null;
      if (outputBuilder_ != null) {
        outputBuilder_.dispose();
        outputBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.JsonOutput.Builder getOutputBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getOutputFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.JsonOutputOrBuilder getOutputOrBuilder() {
      if (outputBuilder_ != null) {
        return outputBuilder_.getMessageOrBuilder();
      } else {
        return output_ == null ?
            com.premiumminds.sonar.postgres.protobuf.JsonOutput.getDefaultInstance() : output_;
      }
    }
    /**
     * <code>.pg_query.JsonOutput output = 1 [json_name = "output"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.JsonOutput, com.premiumminds.sonar.postgres.protobuf.JsonOutput.Builder, com.premiumminds.sonar.postgres.protobuf.JsonOutputOrBuilder> 
        getOutputFieldBuilder() {
      if (outputBuilder_ == null) {
        outputBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.JsonOutput, com.premiumminds.sonar.postgres.protobuf.JsonOutput.Builder, com.premiumminds.sonar.postgres.protobuf.JsonOutputOrBuilder>(
                getOutput(),
                getParentForChildren(),
                isClean());
        output_ = null;
      }
      return outputBuilder_;
    }

    private com.premiumminds.sonar.postgres.protobuf.Node aggFilter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> aggFilterBuilder_;
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     * @return Whether the aggFilter field is set.
     */
    public boolean hasAggFilter() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     * @return The aggFilter.
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getAggFilter() {
      if (aggFilterBuilder_ == null) {
        return aggFilter_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : aggFilter_;
      } else {
        return aggFilterBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     */
    public Builder setAggFilter(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggFilterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        aggFilter_ = value;
      } else {
        aggFilterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     */
    public Builder setAggFilter(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (aggFilterBuilder_ == null) {
        aggFilter_ = builderForValue.build();
      } else {
        aggFilterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     */
    public Builder mergeAggFilter(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggFilterBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          aggFilter_ != null &&
          aggFilter_ != com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance()) {
          getAggFilterBuilder().mergeFrom(value);
        } else {
          aggFilter_ = value;
        }
      } else {
        aggFilterBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     */
    public Builder clearAggFilter() {
      bitField0_ = (bitField0_ & ~0x00000002);
      aggFilter_ = null;
      if (aggFilterBuilder_ != null) {
        aggFilterBuilder_.dispose();
        aggFilterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getAggFilterBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getAggFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getAggFilterOrBuilder() {
      if (aggFilterBuilder_ != null) {
        return aggFilterBuilder_.getMessageOrBuilder();
      } else {
        return aggFilter_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : aggFilter_;
      }
    }
    /**
     * <code>.pg_query.Node agg_filter = 2 [json_name = "agg_filter"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getAggFilterFieldBuilder() {
      if (aggFilterBuilder_ == null) {
        aggFilterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                getAggFilter(),
                getParentForChildren(),
                isClean());
        aggFilter_ = null;
      }
      return aggFilterBuilder_;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> aggOrder_ =
      java.util.Collections.emptyList();
    private void ensureAggOrderIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        aggOrder_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(aggOrder_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> aggOrderBuilder_;

    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getAggOrderList() {
      if (aggOrderBuilder_ == null) {
        return java.util.Collections.unmodifiableList(aggOrder_);
      } else {
        return aggOrderBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public int getAggOrderCount() {
      if (aggOrderBuilder_ == null) {
        return aggOrder_.size();
      } else {
        return aggOrderBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getAggOrder(int index) {
      if (aggOrderBuilder_ == null) {
        return aggOrder_.get(index);
      } else {
        return aggOrderBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder setAggOrder(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggOrderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAggOrderIsMutable();
        aggOrder_.set(index, value);
        onChanged();
      } else {
        aggOrderBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder setAggOrder(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        aggOrder_.set(index, builderForValue.build());
        onChanged();
      } else {
        aggOrderBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAggOrder(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggOrderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAggOrderIsMutable();
        aggOrder_.add(value);
        onChanged();
      } else {
        aggOrderBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAggOrder(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (aggOrderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAggOrderIsMutable();
        aggOrder_.add(index, value);
        onChanged();
      } else {
        aggOrderBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAggOrder(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        aggOrder_.add(builderForValue.build());
        onChanged();
      } else {
        aggOrderBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAggOrder(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        aggOrder_.add(index, builderForValue.build());
        onChanged();
      } else {
        aggOrderBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder addAllAggOrder(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, aggOrder_);
        onChanged();
      } else {
        aggOrderBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder clearAggOrder() {
      if (aggOrderBuilder_ == null) {
        aggOrder_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        aggOrderBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public Builder removeAggOrder(int index) {
      if (aggOrderBuilder_ == null) {
        ensureAggOrderIsMutable();
        aggOrder_.remove(index);
        onChanged();
      } else {
        aggOrderBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getAggOrderBuilder(
        int index) {
      return getAggOrderFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getAggOrderOrBuilder(
        int index) {
      if (aggOrderBuilder_ == null) {
        return aggOrder_.get(index);  } else {
        return aggOrderBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getAggOrderOrBuilderList() {
      if (aggOrderBuilder_ != null) {
        return aggOrderBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(aggOrder_);
      }
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addAggOrderBuilder() {
      return getAggOrderFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addAggOrderBuilder(
        int index) {
      return getAggOrderFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node agg_order = 3 [json_name = "agg_order"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getAggOrderBuilderList() {
      return getAggOrderFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getAggOrderFieldBuilder() {
      if (aggOrderBuilder_ == null) {
        aggOrderBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                aggOrder_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        aggOrder_ = null;
      }
      return aggOrderBuilder_;
    }

    private com.premiumminds.sonar.postgres.protobuf.WindowDef over_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.WindowDef, com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder, com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder> overBuilder_;
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     * @return Whether the over field is set.
     */
    public boolean hasOver() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     * @return The over.
     */
    public com.premiumminds.sonar.postgres.protobuf.WindowDef getOver() {
      if (overBuilder_ == null) {
        return over_ == null ? com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance() : over_;
      } else {
        return overBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     */
    public Builder setOver(com.premiumminds.sonar.postgres.protobuf.WindowDef value) {
      if (overBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        over_ = value;
      } else {
        overBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     */
    public Builder setOver(
        com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder builderForValue) {
      if (overBuilder_ == null) {
        over_ = builderForValue.build();
      } else {
        overBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     */
    public Builder mergeOver(com.premiumminds.sonar.postgres.protobuf.WindowDef value) {
      if (overBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          over_ != null &&
          over_ != com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance()) {
          getOverBuilder().mergeFrom(value);
        } else {
          over_ = value;
        }
      } else {
        overBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     */
    public Builder clearOver() {
      bitField0_ = (bitField0_ & ~0x00000008);
      over_ = null;
      if (overBuilder_ != null) {
        overBuilder_.dispose();
        overBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder getOverBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getOverFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder getOverOrBuilder() {
      if (overBuilder_ != null) {
        return overBuilder_.getMessageOrBuilder();
      } else {
        return over_ == null ?
            com.premiumminds.sonar.postgres.protobuf.WindowDef.getDefaultInstance() : over_;
      }
    }
    /**
     * <code>.pg_query.WindowDef over = 4 [json_name = "over"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.WindowDef, com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder, com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder> 
        getOverFieldBuilder() {
      if (overBuilder_ == null) {
        overBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.WindowDef, com.premiumminds.sonar.postgres.protobuf.WindowDef.Builder, com.premiumminds.sonar.postgres.protobuf.WindowDefOrBuilder>(
                getOver(),
                getParentForChildren(),
                isClean());
        over_ = null;
      }
      return overBuilder_;
    }

    private int location_ ;
    /**
     * <code>int32 location = 5 [json_name = "location"];</code>
     * @return The location.
     */
    @java.lang.Override
    public int getLocation() {
      return location_;
    }
    /**
     * <code>int32 location = 5 [json_name = "location"];</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(int value) {
      
      location_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 location = 5 [json_name = "location"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      bitField0_ = (bitField0_ & ~0x00000010);
      location_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pg_query.JsonAggConstructor)
  }

  // @@protoc_insertion_point(class_scope:pg_query.JsonAggConstructor)
  private static final com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor();
  }

  public static com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JsonAggConstructor>
      PARSER = new com.google.protobuf.AbstractParser<JsonAggConstructor>() {
    @java.lang.Override
    public JsonAggConstructor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<JsonAggConstructor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JsonAggConstructor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.JsonAggConstructor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

