// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf enum {@code pg_query.JsonBehaviorType}
 */
public enum JsonBehaviorType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>JSON_BEHAVIOR_TYPE_UNDEFINED = 0;</code>
   */
  JSON_BEHAVIOR_TYPE_UNDEFINED(0),
  /**
   * <code>JSON_BEHAVIOR_NULL = 1;</code>
   */
  JSON_BEHAVIOR_NULL(1),
  /**
   * <code>JSON_BEHAVIOR_ERROR = 2;</code>
   */
  JSON_BEHAVIOR_ERROR(2),
  /**
   * <code>JSON_BEHAVIOR_EMPTY = 3;</code>
   */
  JSON_BEHAVIOR_EMPTY(3),
  /**
   * <code>JSON_BEHAVIOR_TRUE = 4;</code>
   */
  JSON_BEHAVIOR_TRUE(4),
  /**
   * <code>JSON_BEHAVIOR_FALSE = 5;</code>
   */
  JSON_BEHAVIOR_FALSE(5),
  /**
   * <code>JSON_BEHAVIOR_UNKNOWN = 6;</code>
   */
  JSON_BEHAVIOR_UNKNOWN(6),
  /**
   * <code>JSON_BEHAVIOR_EMPTY_ARRAY = 7;</code>
   */
  JSON_BEHAVIOR_EMPTY_ARRAY(7),
  /**
   * <code>JSON_BEHAVIOR_EMPTY_OBJECT = 8;</code>
   */
  JSON_BEHAVIOR_EMPTY_OBJECT(8),
  /**
   * <code>JSON_BEHAVIOR_DEFAULT = 9;</code>
   */
  JSON_BEHAVIOR_DEFAULT(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>JSON_BEHAVIOR_TYPE_UNDEFINED = 0;</code>
   */
  public static final int JSON_BEHAVIOR_TYPE_UNDEFINED_VALUE = 0;
  /**
   * <code>JSON_BEHAVIOR_NULL = 1;</code>
   */
  public static final int JSON_BEHAVIOR_NULL_VALUE = 1;
  /**
   * <code>JSON_BEHAVIOR_ERROR = 2;</code>
   */
  public static final int JSON_BEHAVIOR_ERROR_VALUE = 2;
  /**
   * <code>JSON_BEHAVIOR_EMPTY = 3;</code>
   */
  public static final int JSON_BEHAVIOR_EMPTY_VALUE = 3;
  /**
   * <code>JSON_BEHAVIOR_TRUE = 4;</code>
   */
  public static final int JSON_BEHAVIOR_TRUE_VALUE = 4;
  /**
   * <code>JSON_BEHAVIOR_FALSE = 5;</code>
   */
  public static final int JSON_BEHAVIOR_FALSE_VALUE = 5;
  /**
   * <code>JSON_BEHAVIOR_UNKNOWN = 6;</code>
   */
  public static final int JSON_BEHAVIOR_UNKNOWN_VALUE = 6;
  /**
   * <code>JSON_BEHAVIOR_EMPTY_ARRAY = 7;</code>
   */
  public static final int JSON_BEHAVIOR_EMPTY_ARRAY_VALUE = 7;
  /**
   * <code>JSON_BEHAVIOR_EMPTY_OBJECT = 8;</code>
   */
  public static final int JSON_BEHAVIOR_EMPTY_OBJECT_VALUE = 8;
  /**
   * <code>JSON_BEHAVIOR_DEFAULT = 9;</code>
   */
  public static final int JSON_BEHAVIOR_DEFAULT_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static JsonBehaviorType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static JsonBehaviorType forNumber(int value) {
    switch (value) {
      case 0: return JSON_BEHAVIOR_TYPE_UNDEFINED;
      case 1: return JSON_BEHAVIOR_NULL;
      case 2: return JSON_BEHAVIOR_ERROR;
      case 3: return JSON_BEHAVIOR_EMPTY;
      case 4: return JSON_BEHAVIOR_TRUE;
      case 5: return JSON_BEHAVIOR_FALSE;
      case 6: return JSON_BEHAVIOR_UNKNOWN;
      case 7: return JSON_BEHAVIOR_EMPTY_ARRAY;
      case 8: return JSON_BEHAVIOR_EMPTY_OBJECT;
      case 9: return JSON_BEHAVIOR_DEFAULT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<JsonBehaviorType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      JsonBehaviorType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<JsonBehaviorType>() {
          public JsonBehaviorType findValueByNumber(int number) {
            return JsonBehaviorType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.getDescriptor().getEnumTypes().get(53);
  }

  private static final JsonBehaviorType[] VALUES = values();

  public static JsonBehaviorType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private JsonBehaviorType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:pg_query.JsonBehaviorType)
}

