// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

package com.premiumminds.sonar.postgres.protobuf;

public interface OnConflictClauseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.OnConflictClause)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.pg_query.OnConflictAction action = 1 [json_name = "action"];</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.pg_query.OnConflictAction action = 1 [json_name = "action"];</code>
   * @return The action.
   */
  com.premiumminds.sonar.postgres.protobuf.OnConflictAction getAction();

  /**
   * <code>.pg_query.InferClause infer = 2 [json_name = "infer"];</code>
   * @return Whether the infer field is set.
   */
  boolean hasInfer();
  /**
   * <code>.pg_query.InferClause infer = 2 [json_name = "infer"];</code>
   * @return The infer.
   */
  com.premiumminds.sonar.postgres.protobuf.InferClause getInfer();
  /**
   * <code>.pg_query.InferClause infer = 2 [json_name = "infer"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.InferClauseOrBuilder getInferOrBuilder();

  /**
   * <code>repeated .pg_query.Node target_list = 3 [json_name = "targetList"];</code>
   */
  java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> 
      getTargetListList();
  /**
   * <code>repeated .pg_query.Node target_list = 3 [json_name = "targetList"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.Node getTargetList(int index);
  /**
   * <code>repeated .pg_query.Node target_list = 3 [json_name = "targetList"];</code>
   */
  int getTargetListCount();
  /**
   * <code>repeated .pg_query.Node target_list = 3 [json_name = "targetList"];</code>
   */
  java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getTargetListOrBuilderList();
  /**
   * <code>repeated .pg_query.Node target_list = 3 [json_name = "targetList"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getTargetListOrBuilder(
      int index);

  /**
   * <code>.pg_query.Node where_clause = 4 [json_name = "whereClause"];</code>
   * @return Whether the whereClause field is set.
   */
  boolean hasWhereClause();
  /**
   * <code>.pg_query.Node where_clause = 4 [json_name = "whereClause"];</code>
   * @return The whereClause.
   */
  com.premiumminds.sonar.postgres.protobuf.Node getWhereClause();
  /**
   * <code>.pg_query.Node where_clause = 4 [json_name = "whereClause"];</code>
   */
  com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getWhereClauseOrBuilder();

  /**
   * <code>int32 location = 5 [json_name = "location"];</code>
   * @return The location.
   */
  int getLocation();
}
