// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf type {@code pg_query.RangeTableFunc}
 */
public final class RangeTableFunc extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pg_query.RangeTableFunc)
    RangeTableFuncOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RangeTableFunc.newBuilder() to construct.
  private RangeTableFunc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RangeTableFunc() {
    namespaces_ = java.util.Collections.emptyList();
    columns_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RangeTableFunc();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFunc_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFunc_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.premiumminds.sonar.postgres.protobuf.RangeTableFunc.class, com.premiumminds.sonar.postgres.protobuf.RangeTableFunc.Builder.class);
  }

  public static final int LATERAL_FIELD_NUMBER = 1;
  private boolean lateral_ = false;
  /**
   * <code>bool lateral = 1 [json_name = "lateral"];</code>
   * @return The lateral.
   */
  @java.lang.Override
  public boolean getLateral() {
    return lateral_;
  }

  public static final int DOCEXPR_FIELD_NUMBER = 2;
  private com.premiumminds.sonar.postgres.protobuf.Node docexpr_;
  /**
   * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
   * @return Whether the docexpr field is set.
   */
  @java.lang.Override
  public boolean hasDocexpr() {
    return docexpr_ != null;
  }
  /**
   * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
   * @return The docexpr.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getDocexpr() {
    return docexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : docexpr_;
  }
  /**
   * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getDocexprOrBuilder() {
    return docexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : docexpr_;
  }

  public static final int ROWEXPR_FIELD_NUMBER = 3;
  private com.premiumminds.sonar.postgres.protobuf.Node rowexpr_;
  /**
   * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
   * @return Whether the rowexpr field is set.
   */
  @java.lang.Override
  public boolean hasRowexpr() {
    return rowexpr_ != null;
  }
  /**
   * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
   * @return The rowexpr.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getRowexpr() {
    return rowexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : rowexpr_;
  }
  /**
   * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getRowexprOrBuilder() {
    return rowexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : rowexpr_;
  }

  public static final int NAMESPACES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> namespaces_;
  /**
   * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getNamespacesList() {
    return namespaces_;
  }
  /**
   * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getNamespacesOrBuilderList() {
    return namespaces_;
  }
  /**
   * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
   */
  @java.lang.Override
  public int getNamespacesCount() {
    return namespaces_.size();
  }
  /**
   * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getNamespaces(int index) {
    return namespaces_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getNamespacesOrBuilder(
      int index) {
    return namespaces_.get(index);
  }

  public static final int COLUMNS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> columns_;
  /**
   * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getColumnsList() {
    return columns_;
  }
  /**
   * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getColumnsOrBuilderList() {
    return columns_;
  }
  /**
   * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
   */
  @java.lang.Override
  public int getColumnsCount() {
    return columns_.size();
  }
  /**
   * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getColumns(int index) {
    return columns_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColumnsOrBuilder(
      int index) {
    return columns_.get(index);
  }

  public static final int ALIAS_FIELD_NUMBER = 6;
  private com.premiumminds.sonar.postgres.protobuf.Alias alias_;
  /**
   * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
   * @return Whether the alias field is set.
   */
  @java.lang.Override
  public boolean hasAlias() {
    return alias_ != null;
  }
  /**
   * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
   * @return The alias.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Alias getAlias() {
    return alias_ == null ? com.premiumminds.sonar.postgres.protobuf.Alias.getDefaultInstance() : alias_;
  }
  /**
   * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.AliasOrBuilder getAliasOrBuilder() {
    return alias_ == null ? com.premiumminds.sonar.postgres.protobuf.Alias.getDefaultInstance() : alias_;
  }

  public static final int LOCATION_FIELD_NUMBER = 7;
  private int location_ = 0;
  /**
   * <code>int32 location = 7 [json_name = "location"];</code>
   * @return The location.
   */
  @java.lang.Override
  public int getLocation() {
    return location_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lateral_ != false) {
      output.writeBool(1, lateral_);
    }
    if (docexpr_ != null) {
      output.writeMessage(2, getDocexpr());
    }
    if (rowexpr_ != null) {
      output.writeMessage(3, getRowexpr());
    }
    for (int i = 0; i < namespaces_.size(); i++) {
      output.writeMessage(4, namespaces_.get(i));
    }
    for (int i = 0; i < columns_.size(); i++) {
      output.writeMessage(5, columns_.get(i));
    }
    if (alias_ != null) {
      output.writeMessage(6, getAlias());
    }
    if (location_ != 0) {
      output.writeInt32(7, location_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (lateral_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, lateral_);
    }
    if (docexpr_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDocexpr());
    }
    if (rowexpr_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRowexpr());
    }
    for (int i = 0; i < namespaces_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, namespaces_.get(i));
    }
    for (int i = 0; i < columns_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, columns_.get(i));
    }
    if (alias_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getAlias());
    }
    if (location_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, location_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.premiumminds.sonar.postgres.protobuf.RangeTableFunc)) {
      return super.equals(obj);
    }
    com.premiumminds.sonar.postgres.protobuf.RangeTableFunc other = (com.premiumminds.sonar.postgres.protobuf.RangeTableFunc) obj;

    if (getLateral()
        != other.getLateral()) return false;
    if (hasDocexpr() != other.hasDocexpr()) return false;
    if (hasDocexpr()) {
      if (!getDocexpr()
          .equals(other.getDocexpr())) return false;
    }
    if (hasRowexpr() != other.hasRowexpr()) return false;
    if (hasRowexpr()) {
      if (!getRowexpr()
          .equals(other.getRowexpr())) return false;
    }
    if (!getNamespacesList()
        .equals(other.getNamespacesList())) return false;
    if (!getColumnsList()
        .equals(other.getColumnsList())) return false;
    if (hasAlias() != other.hasAlias()) return false;
    if (hasAlias()) {
      if (!getAlias()
          .equals(other.getAlias())) return false;
    }
    if (getLocation()
        != other.getLocation()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LATERAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getLateral());
    if (hasDocexpr()) {
      hash = (37 * hash) + DOCEXPR_FIELD_NUMBER;
      hash = (53 * hash) + getDocexpr().hashCode();
    }
    if (hasRowexpr()) {
      hash = (37 * hash) + ROWEXPR_FIELD_NUMBER;
      hash = (53 * hash) + getRowexpr().hashCode();
    }
    if (getNamespacesCount() > 0) {
      hash = (37 * hash) + NAMESPACES_FIELD_NUMBER;
      hash = (53 * hash) + getNamespacesList().hashCode();
    }
    if (getColumnsCount() > 0) {
      hash = (37 * hash) + COLUMNS_FIELD_NUMBER;
      hash = (53 * hash) + getColumnsList().hashCode();
    }
    if (hasAlias()) {
      hash = (37 * hash) + ALIAS_FIELD_NUMBER;
      hash = (53 * hash) + getAlias().hashCode();
    }
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.premiumminds.sonar.postgres.protobuf.RangeTableFunc prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pg_query.RangeTableFunc}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pg_query.RangeTableFunc)
      com.premiumminds.sonar.postgres.protobuf.RangeTableFuncOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFunc_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFunc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premiumminds.sonar.postgres.protobuf.RangeTableFunc.class, com.premiumminds.sonar.postgres.protobuf.RangeTableFunc.Builder.class);
    }

    // Construct using com.premiumminds.sonar.postgres.protobuf.RangeTableFunc.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lateral_ = false;
      docexpr_ = null;
      if (docexprBuilder_ != null) {
        docexprBuilder_.dispose();
        docexprBuilder_ = null;
      }
      rowexpr_ = null;
      if (rowexprBuilder_ != null) {
        rowexprBuilder_.dispose();
        rowexprBuilder_ = null;
      }
      if (namespacesBuilder_ == null) {
        namespaces_ = java.util.Collections.emptyList();
      } else {
        namespaces_ = null;
        namespacesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
      } else {
        columns_ = null;
        columnsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      alias_ = null;
      if (aliasBuilder_ != null) {
        aliasBuilder_.dispose();
        aliasBuilder_ = null;
      }
      location_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFunc_descriptor;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.RangeTableFunc getDefaultInstanceForType() {
      return com.premiumminds.sonar.postgres.protobuf.RangeTableFunc.getDefaultInstance();
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.RangeTableFunc build() {
      com.premiumminds.sonar.postgres.protobuf.RangeTableFunc result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.RangeTableFunc buildPartial() {
      com.premiumminds.sonar.postgres.protobuf.RangeTableFunc result = new com.premiumminds.sonar.postgres.protobuf.RangeTableFunc(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.premiumminds.sonar.postgres.protobuf.RangeTableFunc result) {
      if (namespacesBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          namespaces_ = java.util.Collections.unmodifiableList(namespaces_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.namespaces_ = namespaces_;
      } else {
        result.namespaces_ = namespacesBuilder_.build();
      }
      if (columnsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          columns_ = java.util.Collections.unmodifiableList(columns_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.columns_ = columns_;
      } else {
        result.columns_ = columnsBuilder_.build();
      }
    }

    private void buildPartial0(com.premiumminds.sonar.postgres.protobuf.RangeTableFunc result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lateral_ = lateral_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.docexpr_ = docexprBuilder_ == null
            ? docexpr_
            : docexprBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.rowexpr_ = rowexprBuilder_ == null
            ? rowexpr_
            : rowexprBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.alias_ = aliasBuilder_ == null
            ? alias_
            : aliasBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.location_ = location_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.premiumminds.sonar.postgres.protobuf.RangeTableFunc) {
        return mergeFrom((com.premiumminds.sonar.postgres.protobuf.RangeTableFunc)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.premiumminds.sonar.postgres.protobuf.RangeTableFunc other) {
      if (other == com.premiumminds.sonar.postgres.protobuf.RangeTableFunc.getDefaultInstance()) return this;
      if (other.getLateral() != false) {
        setLateral(other.getLateral());
      }
      if (other.hasDocexpr()) {
        mergeDocexpr(other.getDocexpr());
      }
      if (other.hasRowexpr()) {
        mergeRowexpr(other.getRowexpr());
      }
      if (namespacesBuilder_ == null) {
        if (!other.namespaces_.isEmpty()) {
          if (namespaces_.isEmpty()) {
            namespaces_ = other.namespaces_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureNamespacesIsMutable();
            namespaces_.addAll(other.namespaces_);
          }
          onChanged();
        }
      } else {
        if (!other.namespaces_.isEmpty()) {
          if (namespacesBuilder_.isEmpty()) {
            namespacesBuilder_.dispose();
            namespacesBuilder_ = null;
            namespaces_ = other.namespaces_;
            bitField0_ = (bitField0_ & ~0x00000008);
            namespacesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNamespacesFieldBuilder() : null;
          } else {
            namespacesBuilder_.addAllMessages(other.namespaces_);
          }
        }
      }
      if (columnsBuilder_ == null) {
        if (!other.columns_.isEmpty()) {
          if (columns_.isEmpty()) {
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureColumnsIsMutable();
            columns_.addAll(other.columns_);
          }
          onChanged();
        }
      } else {
        if (!other.columns_.isEmpty()) {
          if (columnsBuilder_.isEmpty()) {
            columnsBuilder_.dispose();
            columnsBuilder_ = null;
            columns_ = other.columns_;
            bitField0_ = (bitField0_ & ~0x00000010);
            columnsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getColumnsFieldBuilder() : null;
          } else {
            columnsBuilder_.addAllMessages(other.columns_);
          }
        }
      }
      if (other.hasAlias()) {
        mergeAlias(other.getAlias());
      }
      if (other.getLocation() != 0) {
        setLocation(other.getLocation());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              lateral_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getDocexprFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getRowexprFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (namespacesBuilder_ == null) {
                ensureNamespacesIsMutable();
                namespaces_.add(m);
              } else {
                namespacesBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (columnsBuilder_ == null) {
                ensureColumnsIsMutable();
                columns_.add(m);
              } else {
                columnsBuilder_.addMessage(m);
              }
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getAliasFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              location_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean lateral_ ;
    /**
     * <code>bool lateral = 1 [json_name = "lateral"];</code>
     * @return The lateral.
     */
    @java.lang.Override
    public boolean getLateral() {
      return lateral_;
    }
    /**
     * <code>bool lateral = 1 [json_name = "lateral"];</code>
     * @param value The lateral to set.
     * @return This builder for chaining.
     */
    public Builder setLateral(boolean value) {
      
      lateral_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool lateral = 1 [json_name = "lateral"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLateral() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lateral_ = false;
      onChanged();
      return this;
    }

    private com.premiumminds.sonar.postgres.protobuf.Node docexpr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> docexprBuilder_;
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     * @return Whether the docexpr field is set.
     */
    public boolean hasDocexpr() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     * @return The docexpr.
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getDocexpr() {
      if (docexprBuilder_ == null) {
        return docexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : docexpr_;
      } else {
        return docexprBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     */
    public Builder setDocexpr(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (docexprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        docexpr_ = value;
      } else {
        docexprBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     */
    public Builder setDocexpr(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (docexprBuilder_ == null) {
        docexpr_ = builderForValue.build();
      } else {
        docexprBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     */
    public Builder mergeDocexpr(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (docexprBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          docexpr_ != null &&
          docexpr_ != com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance()) {
          getDocexprBuilder().mergeFrom(value);
        } else {
          docexpr_ = value;
        }
      } else {
        docexprBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     */
    public Builder clearDocexpr() {
      bitField0_ = (bitField0_ & ~0x00000002);
      docexpr_ = null;
      if (docexprBuilder_ != null) {
        docexprBuilder_.dispose();
        docexprBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getDocexprBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getDocexprFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getDocexprOrBuilder() {
      if (docexprBuilder_ != null) {
        return docexprBuilder_.getMessageOrBuilder();
      } else {
        return docexpr_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : docexpr_;
      }
    }
    /**
     * <code>.pg_query.Node docexpr = 2 [json_name = "docexpr"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getDocexprFieldBuilder() {
      if (docexprBuilder_ == null) {
        docexprBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                getDocexpr(),
                getParentForChildren(),
                isClean());
        docexpr_ = null;
      }
      return docexprBuilder_;
    }

    private com.premiumminds.sonar.postgres.protobuf.Node rowexpr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> rowexprBuilder_;
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     * @return Whether the rowexpr field is set.
     */
    public boolean hasRowexpr() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     * @return The rowexpr.
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getRowexpr() {
      if (rowexprBuilder_ == null) {
        return rowexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : rowexpr_;
      } else {
        return rowexprBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     */
    public Builder setRowexpr(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (rowexprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        rowexpr_ = value;
      } else {
        rowexprBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     */
    public Builder setRowexpr(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (rowexprBuilder_ == null) {
        rowexpr_ = builderForValue.build();
      } else {
        rowexprBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     */
    public Builder mergeRowexpr(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (rowexprBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          rowexpr_ != null &&
          rowexpr_ != com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance()) {
          getRowexprBuilder().mergeFrom(value);
        } else {
          rowexpr_ = value;
        }
      } else {
        rowexprBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     */
    public Builder clearRowexpr() {
      bitField0_ = (bitField0_ & ~0x00000004);
      rowexpr_ = null;
      if (rowexprBuilder_ != null) {
        rowexprBuilder_.dispose();
        rowexprBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getRowexprBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getRowexprFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getRowexprOrBuilder() {
      if (rowexprBuilder_ != null) {
        return rowexprBuilder_.getMessageOrBuilder();
      } else {
        return rowexpr_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : rowexpr_;
      }
    }
    /**
     * <code>.pg_query.Node rowexpr = 3 [json_name = "rowexpr"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getRowexprFieldBuilder() {
      if (rowexprBuilder_ == null) {
        rowexprBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                getRowexpr(),
                getParentForChildren(),
                isClean());
        rowexpr_ = null;
      }
      return rowexprBuilder_;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> namespaces_ =
      java.util.Collections.emptyList();
    private void ensureNamespacesIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        namespaces_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(namespaces_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> namespacesBuilder_;

    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getNamespacesList() {
      if (namespacesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(namespaces_);
      } else {
        return namespacesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public int getNamespacesCount() {
      if (namespacesBuilder_ == null) {
        return namespaces_.size();
      } else {
        return namespacesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getNamespaces(int index) {
      if (namespacesBuilder_ == null) {
        return namespaces_.get(index);
      } else {
        return namespacesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder setNamespaces(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (namespacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamespacesIsMutable();
        namespaces_.set(index, value);
        onChanged();
      } else {
        namespacesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder setNamespaces(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        namespaces_.set(index, builderForValue.build());
        onChanged();
      } else {
        namespacesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder addNamespaces(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (namespacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamespacesIsMutable();
        namespaces_.add(value);
        onChanged();
      } else {
        namespacesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder addNamespaces(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (namespacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamespacesIsMutable();
        namespaces_.add(index, value);
        onChanged();
      } else {
        namespacesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder addNamespaces(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        namespaces_.add(builderForValue.build());
        onChanged();
      } else {
        namespacesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder addNamespaces(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        namespaces_.add(index, builderForValue.build());
        onChanged();
      } else {
        namespacesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder addAllNamespaces(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, namespaces_);
        onChanged();
      } else {
        namespacesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder clearNamespaces() {
      if (namespacesBuilder_ == null) {
        namespaces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        namespacesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public Builder removeNamespaces(int index) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        namespaces_.remove(index);
        onChanged();
      } else {
        namespacesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getNamespacesBuilder(
        int index) {
      return getNamespacesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getNamespacesOrBuilder(
        int index) {
      if (namespacesBuilder_ == null) {
        return namespaces_.get(index);  } else {
        return namespacesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getNamespacesOrBuilderList() {
      if (namespacesBuilder_ != null) {
        return namespacesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(namespaces_);
      }
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addNamespacesBuilder() {
      return getNamespacesFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addNamespacesBuilder(
        int index) {
      return getNamespacesFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node namespaces = 4 [json_name = "namespaces"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getNamespacesBuilderList() {
      return getNamespacesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getNamespacesFieldBuilder() {
      if (namespacesBuilder_ == null) {
        namespacesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                namespaces_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        namespaces_ = null;
      }
      return namespacesBuilder_;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> columns_ =
      java.util.Collections.emptyList();
    private void ensureColumnsIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        columns_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(columns_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> columnsBuilder_;

    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getColumnsList() {
      if (columnsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(columns_);
      } else {
        return columnsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public int getColumnsCount() {
      if (columnsBuilder_ == null) {
        return columns_.size();
      } else {
        return columnsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getColumns(int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);
      } else {
        return columnsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder setColumns(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.set(index, value);
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder setColumns(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.set(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder addColumns(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder addColumns(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (columnsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColumnsIsMutable();
        columns_.add(index, value);
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder addColumns(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder addColumns(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.add(index, builderForValue.build());
        onChanged();
      } else {
        columnsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder addAllColumns(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, columns_);
        onChanged();
      } else {
        columnsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder clearColumns() {
      if (columnsBuilder_ == null) {
        columns_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        columnsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public Builder removeColumns(int index) {
      if (columnsBuilder_ == null) {
        ensureColumnsIsMutable();
        columns_.remove(index);
        onChanged();
      } else {
        columnsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColumnsOrBuilder(
        int index) {
      if (columnsBuilder_ == null) {
        return columns_.get(index);  } else {
        return columnsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getColumnsOrBuilderList() {
      if (columnsBuilder_ != null) {
        return columnsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(columns_);
      }
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addColumnsBuilder() {
      return getColumnsFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addColumnsBuilder(
        int index) {
      return getColumnsFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node columns = 5 [json_name = "columns"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getColumnsBuilderList() {
      return getColumnsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getColumnsFieldBuilder() {
      if (columnsBuilder_ == null) {
        columnsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                columns_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        columns_ = null;
      }
      return columnsBuilder_;
    }

    private com.premiumminds.sonar.postgres.protobuf.Alias alias_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Alias, com.premiumminds.sonar.postgres.protobuf.Alias.Builder, com.premiumminds.sonar.postgres.protobuf.AliasOrBuilder> aliasBuilder_;
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     * @return Whether the alias field is set.
     */
    public boolean hasAlias() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     * @return The alias.
     */
    public com.premiumminds.sonar.postgres.protobuf.Alias getAlias() {
      if (aliasBuilder_ == null) {
        return alias_ == null ? com.premiumminds.sonar.postgres.protobuf.Alias.getDefaultInstance() : alias_;
      } else {
        return aliasBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     */
    public Builder setAlias(com.premiumminds.sonar.postgres.protobuf.Alias value) {
      if (aliasBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        alias_ = value;
      } else {
        aliasBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     */
    public Builder setAlias(
        com.premiumminds.sonar.postgres.protobuf.Alias.Builder builderForValue) {
      if (aliasBuilder_ == null) {
        alias_ = builderForValue.build();
      } else {
        aliasBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     */
    public Builder mergeAlias(com.premiumminds.sonar.postgres.protobuf.Alias value) {
      if (aliasBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          alias_ != null &&
          alias_ != com.premiumminds.sonar.postgres.protobuf.Alias.getDefaultInstance()) {
          getAliasBuilder().mergeFrom(value);
        } else {
          alias_ = value;
        }
      } else {
        aliasBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     */
    public Builder clearAlias() {
      bitField0_ = (bitField0_ & ~0x00000020);
      alias_ = null;
      if (aliasBuilder_ != null) {
        aliasBuilder_.dispose();
        aliasBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Alias.Builder getAliasBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getAliasFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.AliasOrBuilder getAliasOrBuilder() {
      if (aliasBuilder_ != null) {
        return aliasBuilder_.getMessageOrBuilder();
      } else {
        return alias_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Alias.getDefaultInstance() : alias_;
      }
    }
    /**
     * <code>.pg_query.Alias alias = 6 [json_name = "alias"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Alias, com.premiumminds.sonar.postgres.protobuf.Alias.Builder, com.premiumminds.sonar.postgres.protobuf.AliasOrBuilder> 
        getAliasFieldBuilder() {
      if (aliasBuilder_ == null) {
        aliasBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Alias, com.premiumminds.sonar.postgres.protobuf.Alias.Builder, com.premiumminds.sonar.postgres.protobuf.AliasOrBuilder>(
                getAlias(),
                getParentForChildren(),
                isClean());
        alias_ = null;
      }
      return aliasBuilder_;
    }

    private int location_ ;
    /**
     * <code>int32 location = 7 [json_name = "location"];</code>
     * @return The location.
     */
    @java.lang.Override
    public int getLocation() {
      return location_;
    }
    /**
     * <code>int32 location = 7 [json_name = "location"];</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(int value) {
      
      location_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 location = 7 [json_name = "location"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      bitField0_ = (bitField0_ & ~0x00000040);
      location_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pg_query.RangeTableFunc)
  }

  // @@protoc_insertion_point(class_scope:pg_query.RangeTableFunc)
  private static final com.premiumminds.sonar.postgres.protobuf.RangeTableFunc DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.premiumminds.sonar.postgres.protobuf.RangeTableFunc();
  }

  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFunc getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RangeTableFunc>
      PARSER = new com.google.protobuf.AbstractParser<RangeTableFunc>() {
    @java.lang.Override
    public RangeTableFunc parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RangeTableFunc> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RangeTableFunc> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.RangeTableFunc getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

