// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf type {@code pg_query.RangeTableFuncCol}
 */
public final class RangeTableFuncCol extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pg_query.RangeTableFuncCol)
    RangeTableFuncColOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RangeTableFuncCol.newBuilder() to construct.
  private RangeTableFuncCol(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RangeTableFuncCol() {
    colname_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RangeTableFuncCol();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFuncCol_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFuncCol_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol.class, com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol.Builder.class);
  }

  private int bitField0_;
  public static final int COLNAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object colname_ = "";
  /**
   * <code>string colname = 1 [json_name = "colname"];</code>
   * @return The colname.
   */
  @java.lang.Override
  public java.lang.String getColname() {
    java.lang.Object ref = colname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      colname_ = s;
      return s;
    }
  }
  /**
   * <code>string colname = 1 [json_name = "colname"];</code>
   * @return The bytes for colname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getColnameBytes() {
    java.lang.Object ref = colname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      colname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_NAME_FIELD_NUMBER = 2;
  private com.premiumminds.sonar.postgres.protobuf.TypeName typeName_;
  /**
   * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
   * @return Whether the typeName field is set.
   */
  @java.lang.Override
  public boolean hasTypeName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
   * @return The typeName.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.TypeName getTypeName() {
    return typeName_ == null ? com.premiumminds.sonar.postgres.protobuf.TypeName.getDefaultInstance() : typeName_;
  }
  /**
   * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.TypeNameOrBuilder getTypeNameOrBuilder() {
    return typeName_ == null ? com.premiumminds.sonar.postgres.protobuf.TypeName.getDefaultInstance() : typeName_;
  }

  public static final int FOR_ORDINALITY_FIELD_NUMBER = 3;
  private boolean forOrdinality_ = false;
  /**
   * <code>bool for_ordinality = 3 [json_name = "for_ordinality"];</code>
   * @return The forOrdinality.
   */
  @java.lang.Override
  public boolean getForOrdinality() {
    return forOrdinality_;
  }

  public static final int IS_NOT_NULL_FIELD_NUMBER = 4;
  private boolean isNotNull_ = false;
  /**
   * <code>bool is_not_null = 4 [json_name = "is_not_null"];</code>
   * @return The isNotNull.
   */
  @java.lang.Override
  public boolean getIsNotNull() {
    return isNotNull_;
  }

  public static final int COLEXPR_FIELD_NUMBER = 5;
  private com.premiumminds.sonar.postgres.protobuf.Node colexpr_;
  /**
   * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
   * @return Whether the colexpr field is set.
   */
  @java.lang.Override
  public boolean hasColexpr() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
   * @return The colexpr.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getColexpr() {
    return colexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : colexpr_;
  }
  /**
   * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColexprOrBuilder() {
    return colexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : colexpr_;
  }

  public static final int COLDEFEXPR_FIELD_NUMBER = 6;
  private com.premiumminds.sonar.postgres.protobuf.Node coldefexpr_;
  /**
   * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
   * @return Whether the coldefexpr field is set.
   */
  @java.lang.Override
  public boolean hasColdefexpr() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
   * @return The coldefexpr.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getColdefexpr() {
    return coldefexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : coldefexpr_;
  }
  /**
   * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColdefexprOrBuilder() {
    return coldefexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : coldefexpr_;
  }

  public static final int LOCATION_FIELD_NUMBER = 7;
  private int location_ = 0;
  /**
   * <code>int32 location = 7 [json_name = "location"];</code>
   * @return The location.
   */
  @java.lang.Override
  public int getLocation() {
    return location_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, colname_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTypeName());
    }
    if (forOrdinality_ != false) {
      output.writeBool(3, forOrdinality_);
    }
    if (isNotNull_ != false) {
      output.writeBool(4, isNotNull_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(5, getColexpr());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(6, getColdefexpr());
    }
    if (location_ != 0) {
      output.writeInt32(7, location_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(colname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, colname_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTypeName());
    }
    if (forOrdinality_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, forOrdinality_);
    }
    if (isNotNull_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isNotNull_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getColexpr());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getColdefexpr());
    }
    if (location_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, location_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol)) {
      return super.equals(obj);
    }
    com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol other = (com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol) obj;

    if (!getColname()
        .equals(other.getColname())) return false;
    if (hasTypeName() != other.hasTypeName()) return false;
    if (hasTypeName()) {
      if (!getTypeName()
          .equals(other.getTypeName())) return false;
    }
    if (getForOrdinality()
        != other.getForOrdinality()) return false;
    if (getIsNotNull()
        != other.getIsNotNull()) return false;
    if (hasColexpr() != other.hasColexpr()) return false;
    if (hasColexpr()) {
      if (!getColexpr()
          .equals(other.getColexpr())) return false;
    }
    if (hasColdefexpr() != other.hasColdefexpr()) return false;
    if (hasColdefexpr()) {
      if (!getColdefexpr()
          .equals(other.getColdefexpr())) return false;
    }
    if (getLocation()
        != other.getLocation()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COLNAME_FIELD_NUMBER;
    hash = (53 * hash) + getColname().hashCode();
    if (hasTypeName()) {
      hash = (37 * hash) + TYPE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTypeName().hashCode();
    }
    hash = (37 * hash) + FOR_ORDINALITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getForOrdinality());
    hash = (37 * hash) + IS_NOT_NULL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsNotNull());
    if (hasColexpr()) {
      hash = (37 * hash) + COLEXPR_FIELD_NUMBER;
      hash = (53 * hash) + getColexpr().hashCode();
    }
    if (hasColdefexpr()) {
      hash = (37 * hash) + COLDEFEXPR_FIELD_NUMBER;
      hash = (53 * hash) + getColdefexpr().hashCode();
    }
    hash = (37 * hash) + LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getLocation();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pg_query.RangeTableFuncCol}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pg_query.RangeTableFuncCol)
      com.premiumminds.sonar.postgres.protobuf.RangeTableFuncColOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFuncCol_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFuncCol_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol.class, com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol.Builder.class);
    }

    // Construct using com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTypeNameFieldBuilder();
        getColexprFieldBuilder();
        getColdefexprFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      colname_ = "";
      typeName_ = null;
      if (typeNameBuilder_ != null) {
        typeNameBuilder_.dispose();
        typeNameBuilder_ = null;
      }
      forOrdinality_ = false;
      isNotNull_ = false;
      colexpr_ = null;
      if (colexprBuilder_ != null) {
        colexprBuilder_.dispose();
        colexprBuilder_ = null;
      }
      coldefexpr_ = null;
      if (coldefexprBuilder_ != null) {
        coldefexprBuilder_.dispose();
        coldefexprBuilder_ = null;
      }
      location_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_RangeTableFuncCol_descriptor;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol getDefaultInstanceForType() {
      return com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol.getDefaultInstance();
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol build() {
      com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol buildPartial() {
      com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol result = new com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.colname_ = colname_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.typeName_ = typeNameBuilder_ == null
            ? typeName_
            : typeNameBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.forOrdinality_ = forOrdinality_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.isNotNull_ = isNotNull_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.colexpr_ = colexprBuilder_ == null
            ? colexpr_
            : colexprBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.coldefexpr_ = coldefexprBuilder_ == null
            ? coldefexpr_
            : coldefexprBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.location_ = location_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol) {
        return mergeFrom((com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol other) {
      if (other == com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol.getDefaultInstance()) return this;
      if (!other.getColname().isEmpty()) {
        colname_ = other.colname_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasTypeName()) {
        mergeTypeName(other.getTypeName());
      }
      if (other.getForOrdinality() != false) {
        setForOrdinality(other.getForOrdinality());
      }
      if (other.getIsNotNull() != false) {
        setIsNotNull(other.getIsNotNull());
      }
      if (other.hasColexpr()) {
        mergeColexpr(other.getColexpr());
      }
      if (other.hasColdefexpr()) {
        mergeColdefexpr(other.getColdefexpr());
      }
      if (other.getLocation() != 0) {
        setLocation(other.getLocation());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              colname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getTypeNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              forOrdinality_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              isNotNull_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getColexprFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getColdefexprFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              location_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object colname_ = "";
    /**
     * <code>string colname = 1 [json_name = "colname"];</code>
     * @return The colname.
     */
    public java.lang.String getColname() {
      java.lang.Object ref = colname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        colname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string colname = 1 [json_name = "colname"];</code>
     * @return The bytes for colname.
     */
    public com.google.protobuf.ByteString
        getColnameBytes() {
      java.lang.Object ref = colname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        colname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string colname = 1 [json_name = "colname"];</code>
     * @param value The colname to set.
     * @return This builder for chaining.
     */
    public Builder setColname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      colname_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string colname = 1 [json_name = "colname"];</code>
     * @return This builder for chaining.
     */
    public Builder clearColname() {
      colname_ = getDefaultInstance().getColname();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string colname = 1 [json_name = "colname"];</code>
     * @param value The bytes for colname to set.
     * @return This builder for chaining.
     */
    public Builder setColnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      colname_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.premiumminds.sonar.postgres.protobuf.TypeName typeName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.TypeName, com.premiumminds.sonar.postgres.protobuf.TypeName.Builder, com.premiumminds.sonar.postgres.protobuf.TypeNameOrBuilder> typeNameBuilder_;
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     * @return Whether the typeName field is set.
     */
    public boolean hasTypeName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     * @return The typeName.
     */
    public com.premiumminds.sonar.postgres.protobuf.TypeName getTypeName() {
      if (typeNameBuilder_ == null) {
        return typeName_ == null ? com.premiumminds.sonar.postgres.protobuf.TypeName.getDefaultInstance() : typeName_;
      } else {
        return typeNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     */
    public Builder setTypeName(com.premiumminds.sonar.postgres.protobuf.TypeName value) {
      if (typeNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        typeName_ = value;
      } else {
        typeNameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     */
    public Builder setTypeName(
        com.premiumminds.sonar.postgres.protobuf.TypeName.Builder builderForValue) {
      if (typeNameBuilder_ == null) {
        typeName_ = builderForValue.build();
      } else {
        typeNameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     */
    public Builder mergeTypeName(com.premiumminds.sonar.postgres.protobuf.TypeName value) {
      if (typeNameBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          typeName_ != null &&
          typeName_ != com.premiumminds.sonar.postgres.protobuf.TypeName.getDefaultInstance()) {
          getTypeNameBuilder().mergeFrom(value);
        } else {
          typeName_ = value;
        }
      } else {
        typeNameBuilder_.mergeFrom(value);
      }
      if (typeName_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     */
    public Builder clearTypeName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      typeName_ = null;
      if (typeNameBuilder_ != null) {
        typeNameBuilder_.dispose();
        typeNameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.TypeName.Builder getTypeNameBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTypeNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.TypeNameOrBuilder getTypeNameOrBuilder() {
      if (typeNameBuilder_ != null) {
        return typeNameBuilder_.getMessageOrBuilder();
      } else {
        return typeName_ == null ?
            com.premiumminds.sonar.postgres.protobuf.TypeName.getDefaultInstance() : typeName_;
      }
    }
    /**
     * <code>.pg_query.TypeName type_name = 2 [json_name = "typeName"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.TypeName, com.premiumminds.sonar.postgres.protobuf.TypeName.Builder, com.premiumminds.sonar.postgres.protobuf.TypeNameOrBuilder> 
        getTypeNameFieldBuilder() {
      if (typeNameBuilder_ == null) {
        typeNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.TypeName, com.premiumminds.sonar.postgres.protobuf.TypeName.Builder, com.premiumminds.sonar.postgres.protobuf.TypeNameOrBuilder>(
                getTypeName(),
                getParentForChildren(),
                isClean());
        typeName_ = null;
      }
      return typeNameBuilder_;
    }

    private boolean forOrdinality_ ;
    /**
     * <code>bool for_ordinality = 3 [json_name = "for_ordinality"];</code>
     * @return The forOrdinality.
     */
    @java.lang.Override
    public boolean getForOrdinality() {
      return forOrdinality_;
    }
    /**
     * <code>bool for_ordinality = 3 [json_name = "for_ordinality"];</code>
     * @param value The forOrdinality to set.
     * @return This builder for chaining.
     */
    public Builder setForOrdinality(boolean value) {

      forOrdinality_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool for_ordinality = 3 [json_name = "for_ordinality"];</code>
     * @return This builder for chaining.
     */
    public Builder clearForOrdinality() {
      bitField0_ = (bitField0_ & ~0x00000004);
      forOrdinality_ = false;
      onChanged();
      return this;
    }

    private boolean isNotNull_ ;
    /**
     * <code>bool is_not_null = 4 [json_name = "is_not_null"];</code>
     * @return The isNotNull.
     */
    @java.lang.Override
    public boolean getIsNotNull() {
      return isNotNull_;
    }
    /**
     * <code>bool is_not_null = 4 [json_name = "is_not_null"];</code>
     * @param value The isNotNull to set.
     * @return This builder for chaining.
     */
    public Builder setIsNotNull(boolean value) {

      isNotNull_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_not_null = 4 [json_name = "is_not_null"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIsNotNull() {
      bitField0_ = (bitField0_ & ~0x00000008);
      isNotNull_ = false;
      onChanged();
      return this;
    }

    private com.premiumminds.sonar.postgres.protobuf.Node colexpr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> colexprBuilder_;
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     * @return Whether the colexpr field is set.
     */
    public boolean hasColexpr() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     * @return The colexpr.
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getColexpr() {
      if (colexprBuilder_ == null) {
        return colexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : colexpr_;
      } else {
        return colexprBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     */
    public Builder setColexpr(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (colexprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        colexpr_ = value;
      } else {
        colexprBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     */
    public Builder setColexpr(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (colexprBuilder_ == null) {
        colexpr_ = builderForValue.build();
      } else {
        colexprBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     */
    public Builder mergeColexpr(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (colexprBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          colexpr_ != null &&
          colexpr_ != com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance()) {
          getColexprBuilder().mergeFrom(value);
        } else {
          colexpr_ = value;
        }
      } else {
        colexprBuilder_.mergeFrom(value);
      }
      if (colexpr_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     */
    public Builder clearColexpr() {
      bitField0_ = (bitField0_ & ~0x00000010);
      colexpr_ = null;
      if (colexprBuilder_ != null) {
        colexprBuilder_.dispose();
        colexprBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getColexprBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getColexprFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColexprOrBuilder() {
      if (colexprBuilder_ != null) {
        return colexprBuilder_.getMessageOrBuilder();
      } else {
        return colexpr_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : colexpr_;
      }
    }
    /**
     * <code>.pg_query.Node colexpr = 5 [json_name = "colexpr"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getColexprFieldBuilder() {
      if (colexprBuilder_ == null) {
        colexprBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                getColexpr(),
                getParentForChildren(),
                isClean());
        colexpr_ = null;
      }
      return colexprBuilder_;
    }

    private com.premiumminds.sonar.postgres.protobuf.Node coldefexpr_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> coldefexprBuilder_;
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     * @return Whether the coldefexpr field is set.
     */
    public boolean hasColdefexpr() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     * @return The coldefexpr.
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getColdefexpr() {
      if (coldefexprBuilder_ == null) {
        return coldefexpr_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : coldefexpr_;
      } else {
        return coldefexprBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     */
    public Builder setColdefexpr(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (coldefexprBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        coldefexpr_ = value;
      } else {
        coldefexprBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     */
    public Builder setColdefexpr(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (coldefexprBuilder_ == null) {
        coldefexpr_ = builderForValue.build();
      } else {
        coldefexprBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     */
    public Builder mergeColdefexpr(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (coldefexprBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          coldefexpr_ != null &&
          coldefexpr_ != com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance()) {
          getColdefexprBuilder().mergeFrom(value);
        } else {
          coldefexpr_ = value;
        }
      } else {
        coldefexprBuilder_.mergeFrom(value);
      }
      if (coldefexpr_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     */
    public Builder clearColdefexpr() {
      bitField0_ = (bitField0_ & ~0x00000020);
      coldefexpr_ = null;
      if (coldefexprBuilder_ != null) {
        coldefexprBuilder_.dispose();
        coldefexprBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getColdefexprBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getColdefexprFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getColdefexprOrBuilder() {
      if (coldefexprBuilder_ != null) {
        return coldefexprBuilder_.getMessageOrBuilder();
      } else {
        return coldefexpr_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : coldefexpr_;
      }
    }
    /**
     * <code>.pg_query.Node coldefexpr = 6 [json_name = "coldefexpr"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getColdefexprFieldBuilder() {
      if (coldefexprBuilder_ == null) {
        coldefexprBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                getColdefexpr(),
                getParentForChildren(),
                isClean());
        coldefexpr_ = null;
      }
      return coldefexprBuilder_;
    }

    private int location_ ;
    /**
     * <code>int32 location = 7 [json_name = "location"];</code>
     * @return The location.
     */
    @java.lang.Override
    public int getLocation() {
      return location_;
    }
    /**
     * <code>int32 location = 7 [json_name = "location"];</code>
     * @param value The location to set.
     * @return This builder for chaining.
     */
    public Builder setLocation(int value) {

      location_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 location = 7 [json_name = "location"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLocation() {
      bitField0_ = (bitField0_ & ~0x00000040);
      location_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pg_query.RangeTableFuncCol)
  }

  // @@protoc_insertion_point(class_scope:pg_query.RangeTableFuncCol)
  private static final com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol();
  }

  public static com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RangeTableFuncCol>
      PARSER = new com.google.protobuf.AbstractParser<RangeTableFuncCol>() {
    @java.lang.Override
    public RangeTableFuncCol parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<RangeTableFuncCol> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RangeTableFuncCol> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.RangeTableFuncCol getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

