// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

// Protobuf Java Version: 3.25.1
package com.premiumminds.sonar.postgres.protobuf;

/**
 * Protobuf type {@code pg_query.WindowClause}
 */
public final class WindowClause extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:pg_query.WindowClause)
    WindowClauseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WindowClause.newBuilder() to construct.
  private WindowClause(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WindowClause() {
    name_ = "";
    refname_ = "";
    partitionClause_ = java.util.Collections.emptyList();
    orderClause_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WindowClause();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_WindowClause_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_WindowClause_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.premiumminds.sonar.postgres.protobuf.WindowClause.class, com.premiumminds.sonar.postgres.protobuf.WindowClause.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REFNAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object refname_ = "";
  /**
   * <code>string refname = 2 [json_name = "refname"];</code>
   * @return The refname.
   */
  @java.lang.Override
  public java.lang.String getRefname() {
    java.lang.Object ref = refname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      refname_ = s;
      return s;
    }
  }
  /**
   * <code>string refname = 2 [json_name = "refname"];</code>
   * @return The bytes for refname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRefnameBytes() {
    java.lang.Object ref = refname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      refname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARTITION_CLAUSE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> partitionClause_;
  /**
   * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getPartitionClauseList() {
    return partitionClause_;
  }
  /**
   * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getPartitionClauseOrBuilderList() {
    return partitionClause_;
  }
  /**
   * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
   */
  @java.lang.Override
  public int getPartitionClauseCount() {
    return partitionClause_.size();
  }
  /**
   * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getPartitionClause(int index) {
    return partitionClause_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getPartitionClauseOrBuilder(
      int index) {
    return partitionClause_.get(index);
  }

  public static final int ORDER_CLAUSE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> orderClause_;
  /**
   * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
   */
  @java.lang.Override
  public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getOrderClauseList() {
    return orderClause_;
  }
  /**
   * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
      getOrderClauseOrBuilderList() {
    return orderClause_;
  }
  /**
   * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
   */
  @java.lang.Override
  public int getOrderClauseCount() {
    return orderClause_.size();
  }
  /**
   * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getOrderClause(int index) {
    return orderClause_.get(index);
  }
  /**
   * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getOrderClauseOrBuilder(
      int index) {
    return orderClause_.get(index);
  }

  public static final int FRAME_OPTIONS_FIELD_NUMBER = 5;
  private int frameOptions_ = 0;
  /**
   * <code>int32 frame_options = 5 [json_name = "frameOptions"];</code>
   * @return The frameOptions.
   */
  @java.lang.Override
  public int getFrameOptions() {
    return frameOptions_;
  }

  public static final int START_OFFSET_FIELD_NUMBER = 6;
  private com.premiumminds.sonar.postgres.protobuf.Node startOffset_;
  /**
   * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
   * @return Whether the startOffset field is set.
   */
  @java.lang.Override
  public boolean hasStartOffset() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
   * @return The startOffset.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getStartOffset() {
    return startOffset_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : startOffset_;
  }
  /**
   * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getStartOffsetOrBuilder() {
    return startOffset_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : startOffset_;
  }

  public static final int END_OFFSET_FIELD_NUMBER = 7;
  private com.premiumminds.sonar.postgres.protobuf.Node endOffset_;
  /**
   * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
   * @return Whether the endOffset field is set.
   */
  @java.lang.Override
  public boolean hasEndOffset() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
   * @return The endOffset.
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.Node getEndOffset() {
    return endOffset_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : endOffset_;
  }
  /**
   * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
   */
  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getEndOffsetOrBuilder() {
    return endOffset_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : endOffset_;
  }

  public static final int START_IN_RANGE_FUNC_FIELD_NUMBER = 8;
  private int startInRangeFunc_ = 0;
  /**
   * <code>uint32 start_in_range_func = 8 [json_name = "startInRangeFunc"];</code>
   * @return The startInRangeFunc.
   */
  @java.lang.Override
  public int getStartInRangeFunc() {
    return startInRangeFunc_;
  }

  public static final int END_IN_RANGE_FUNC_FIELD_NUMBER = 9;
  private int endInRangeFunc_ = 0;
  /**
   * <code>uint32 end_in_range_func = 9 [json_name = "endInRangeFunc"];</code>
   * @return The endInRangeFunc.
   */
  @java.lang.Override
  public int getEndInRangeFunc() {
    return endInRangeFunc_;
  }

  public static final int IN_RANGE_COLL_FIELD_NUMBER = 10;
  private int inRangeColl_ = 0;
  /**
   * <code>uint32 in_range_coll = 10 [json_name = "inRangeColl"];</code>
   * @return The inRangeColl.
   */
  @java.lang.Override
  public int getInRangeColl() {
    return inRangeColl_;
  }

  public static final int IN_RANGE_ASC_FIELD_NUMBER = 11;
  private boolean inRangeAsc_ = false;
  /**
   * <code>bool in_range_asc = 11 [json_name = "inRangeAsc"];</code>
   * @return The inRangeAsc.
   */
  @java.lang.Override
  public boolean getInRangeAsc() {
    return inRangeAsc_;
  }

  public static final int IN_RANGE_NULLS_FIRST_FIELD_NUMBER = 12;
  private boolean inRangeNullsFirst_ = false;
  /**
   * <code>bool in_range_nulls_first = 12 [json_name = "inRangeNullsFirst"];</code>
   * @return The inRangeNullsFirst.
   */
  @java.lang.Override
  public boolean getInRangeNullsFirst() {
    return inRangeNullsFirst_;
  }

  public static final int WINREF_FIELD_NUMBER = 13;
  private int winref_ = 0;
  /**
   * <code>uint32 winref = 13 [json_name = "winref"];</code>
   * @return The winref.
   */
  @java.lang.Override
  public int getWinref() {
    return winref_;
  }

  public static final int COPIED_ORDER_FIELD_NUMBER = 14;
  private boolean copiedOrder_ = false;
  /**
   * <code>bool copied_order = 14 [json_name = "copiedOrder"];</code>
   * @return The copiedOrder.
   */
  @java.lang.Override
  public boolean getCopiedOrder() {
    return copiedOrder_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(refname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, refname_);
    }
    for (int i = 0; i < partitionClause_.size(); i++) {
      output.writeMessage(3, partitionClause_.get(i));
    }
    for (int i = 0; i < orderClause_.size(); i++) {
      output.writeMessage(4, orderClause_.get(i));
    }
    if (frameOptions_ != 0) {
      output.writeInt32(5, frameOptions_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getStartOffset());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(7, getEndOffset());
    }
    if (startInRangeFunc_ != 0) {
      output.writeUInt32(8, startInRangeFunc_);
    }
    if (endInRangeFunc_ != 0) {
      output.writeUInt32(9, endInRangeFunc_);
    }
    if (inRangeColl_ != 0) {
      output.writeUInt32(10, inRangeColl_);
    }
    if (inRangeAsc_ != false) {
      output.writeBool(11, inRangeAsc_);
    }
    if (inRangeNullsFirst_ != false) {
      output.writeBool(12, inRangeNullsFirst_);
    }
    if (winref_ != 0) {
      output.writeUInt32(13, winref_);
    }
    if (copiedOrder_ != false) {
      output.writeBool(14, copiedOrder_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(refname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, refname_);
    }
    for (int i = 0; i < partitionClause_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, partitionClause_.get(i));
    }
    for (int i = 0; i < orderClause_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, orderClause_.get(i));
    }
    if (frameOptions_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, frameOptions_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getStartOffset());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getEndOffset());
    }
    if (startInRangeFunc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(8, startInRangeFunc_);
    }
    if (endInRangeFunc_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(9, endInRangeFunc_);
    }
    if (inRangeColl_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(10, inRangeColl_);
    }
    if (inRangeAsc_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, inRangeAsc_);
    }
    if (inRangeNullsFirst_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, inRangeNullsFirst_);
    }
    if (winref_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(13, winref_);
    }
    if (copiedOrder_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(14, copiedOrder_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.premiumminds.sonar.postgres.protobuf.WindowClause)) {
      return super.equals(obj);
    }
    com.premiumminds.sonar.postgres.protobuf.WindowClause other = (com.premiumminds.sonar.postgres.protobuf.WindowClause) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getRefname()
        .equals(other.getRefname())) return false;
    if (!getPartitionClauseList()
        .equals(other.getPartitionClauseList())) return false;
    if (!getOrderClauseList()
        .equals(other.getOrderClauseList())) return false;
    if (getFrameOptions()
        != other.getFrameOptions()) return false;
    if (hasStartOffset() != other.hasStartOffset()) return false;
    if (hasStartOffset()) {
      if (!getStartOffset()
          .equals(other.getStartOffset())) return false;
    }
    if (hasEndOffset() != other.hasEndOffset()) return false;
    if (hasEndOffset()) {
      if (!getEndOffset()
          .equals(other.getEndOffset())) return false;
    }
    if (getStartInRangeFunc()
        != other.getStartInRangeFunc()) return false;
    if (getEndInRangeFunc()
        != other.getEndInRangeFunc()) return false;
    if (getInRangeColl()
        != other.getInRangeColl()) return false;
    if (getInRangeAsc()
        != other.getInRangeAsc()) return false;
    if (getInRangeNullsFirst()
        != other.getInRangeNullsFirst()) return false;
    if (getWinref()
        != other.getWinref()) return false;
    if (getCopiedOrder()
        != other.getCopiedOrder()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + REFNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRefname().hashCode();
    if (getPartitionClauseCount() > 0) {
      hash = (37 * hash) + PARTITION_CLAUSE_FIELD_NUMBER;
      hash = (53 * hash) + getPartitionClauseList().hashCode();
    }
    if (getOrderClauseCount() > 0) {
      hash = (37 * hash) + ORDER_CLAUSE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderClauseList().hashCode();
    }
    hash = (37 * hash) + FRAME_OPTIONS_FIELD_NUMBER;
    hash = (53 * hash) + getFrameOptions();
    if (hasStartOffset()) {
      hash = (37 * hash) + START_OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getStartOffset().hashCode();
    }
    if (hasEndOffset()) {
      hash = (37 * hash) + END_OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + getEndOffset().hashCode();
    }
    hash = (37 * hash) + START_IN_RANGE_FUNC_FIELD_NUMBER;
    hash = (53 * hash) + getStartInRangeFunc();
    hash = (37 * hash) + END_IN_RANGE_FUNC_FIELD_NUMBER;
    hash = (53 * hash) + getEndInRangeFunc();
    hash = (37 * hash) + IN_RANGE_COLL_FIELD_NUMBER;
    hash = (53 * hash) + getInRangeColl();
    hash = (37 * hash) + IN_RANGE_ASC_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInRangeAsc());
    hash = (37 * hash) + IN_RANGE_NULLS_FIRST_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getInRangeNullsFirst());
    hash = (37 * hash) + WINREF_FIELD_NUMBER;
    hash = (53 * hash) + getWinref();
    hash = (37 * hash) + COPIED_ORDER_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCopiedOrder());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.premiumminds.sonar.postgres.protobuf.WindowClause parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.premiumminds.sonar.postgres.protobuf.WindowClause prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code pg_query.WindowClause}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:pg_query.WindowClause)
      com.premiumminds.sonar.postgres.protobuf.WindowClauseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_WindowClause_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_WindowClause_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.premiumminds.sonar.postgres.protobuf.WindowClause.class, com.premiumminds.sonar.postgres.protobuf.WindowClause.Builder.class);
    }

    // Construct using com.premiumminds.sonar.postgres.protobuf.WindowClause.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPartitionClauseFieldBuilder();
        getOrderClauseFieldBuilder();
        getStartOffsetFieldBuilder();
        getEndOffsetFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      refname_ = "";
      if (partitionClauseBuilder_ == null) {
        partitionClause_ = java.util.Collections.emptyList();
      } else {
        partitionClause_ = null;
        partitionClauseBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (orderClauseBuilder_ == null) {
        orderClause_ = java.util.Collections.emptyList();
      } else {
        orderClause_ = null;
        orderClauseBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      frameOptions_ = 0;
      startOffset_ = null;
      if (startOffsetBuilder_ != null) {
        startOffsetBuilder_.dispose();
        startOffsetBuilder_ = null;
      }
      endOffset_ = null;
      if (endOffsetBuilder_ != null) {
        endOffsetBuilder_.dispose();
        endOffsetBuilder_ = null;
      }
      startInRangeFunc_ = 0;
      endInRangeFunc_ = 0;
      inRangeColl_ = 0;
      inRangeAsc_ = false;
      inRangeNullsFirst_ = false;
      winref_ = 0;
      copiedOrder_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.premiumminds.sonar.postgres.protobuf.PgQuery.internal_static_pg_query_WindowClause_descriptor;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.WindowClause getDefaultInstanceForType() {
      return com.premiumminds.sonar.postgres.protobuf.WindowClause.getDefaultInstance();
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.WindowClause build() {
      com.premiumminds.sonar.postgres.protobuf.WindowClause result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.premiumminds.sonar.postgres.protobuf.WindowClause buildPartial() {
      com.premiumminds.sonar.postgres.protobuf.WindowClause result = new com.premiumminds.sonar.postgres.protobuf.WindowClause(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.premiumminds.sonar.postgres.protobuf.WindowClause result) {
      if (partitionClauseBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          partitionClause_ = java.util.Collections.unmodifiableList(partitionClause_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.partitionClause_ = partitionClause_;
      } else {
        result.partitionClause_ = partitionClauseBuilder_.build();
      }
      if (orderClauseBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          orderClause_ = java.util.Collections.unmodifiableList(orderClause_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.orderClause_ = orderClause_;
      } else {
        result.orderClause_ = orderClauseBuilder_.build();
      }
    }

    private void buildPartial0(com.premiumminds.sonar.postgres.protobuf.WindowClause result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.refname_ = refname_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.frameOptions_ = frameOptions_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.startOffset_ = startOffsetBuilder_ == null
            ? startOffset_
            : startOffsetBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.endOffset_ = endOffsetBuilder_ == null
            ? endOffset_
            : endOffsetBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.startInRangeFunc_ = startInRangeFunc_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.endInRangeFunc_ = endInRangeFunc_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.inRangeColl_ = inRangeColl_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.inRangeAsc_ = inRangeAsc_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.inRangeNullsFirst_ = inRangeNullsFirst_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.winref_ = winref_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.copiedOrder_ = copiedOrder_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.premiumminds.sonar.postgres.protobuf.WindowClause) {
        return mergeFrom((com.premiumminds.sonar.postgres.protobuf.WindowClause)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.premiumminds.sonar.postgres.protobuf.WindowClause other) {
      if (other == com.premiumminds.sonar.postgres.protobuf.WindowClause.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getRefname().isEmpty()) {
        refname_ = other.refname_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (partitionClauseBuilder_ == null) {
        if (!other.partitionClause_.isEmpty()) {
          if (partitionClause_.isEmpty()) {
            partitionClause_ = other.partitionClause_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePartitionClauseIsMutable();
            partitionClause_.addAll(other.partitionClause_);
          }
          onChanged();
        }
      } else {
        if (!other.partitionClause_.isEmpty()) {
          if (partitionClauseBuilder_.isEmpty()) {
            partitionClauseBuilder_.dispose();
            partitionClauseBuilder_ = null;
            partitionClause_ = other.partitionClause_;
            bitField0_ = (bitField0_ & ~0x00000004);
            partitionClauseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPartitionClauseFieldBuilder() : null;
          } else {
            partitionClauseBuilder_.addAllMessages(other.partitionClause_);
          }
        }
      }
      if (orderClauseBuilder_ == null) {
        if (!other.orderClause_.isEmpty()) {
          if (orderClause_.isEmpty()) {
            orderClause_ = other.orderClause_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureOrderClauseIsMutable();
            orderClause_.addAll(other.orderClause_);
          }
          onChanged();
        }
      } else {
        if (!other.orderClause_.isEmpty()) {
          if (orderClauseBuilder_.isEmpty()) {
            orderClauseBuilder_.dispose();
            orderClauseBuilder_ = null;
            orderClause_ = other.orderClause_;
            bitField0_ = (bitField0_ & ~0x00000008);
            orderClauseBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOrderClauseFieldBuilder() : null;
          } else {
            orderClauseBuilder_.addAllMessages(other.orderClause_);
          }
        }
      }
      if (other.getFrameOptions() != 0) {
        setFrameOptions(other.getFrameOptions());
      }
      if (other.hasStartOffset()) {
        mergeStartOffset(other.getStartOffset());
      }
      if (other.hasEndOffset()) {
        mergeEndOffset(other.getEndOffset());
      }
      if (other.getStartInRangeFunc() != 0) {
        setStartInRangeFunc(other.getStartInRangeFunc());
      }
      if (other.getEndInRangeFunc() != 0) {
        setEndInRangeFunc(other.getEndInRangeFunc());
      }
      if (other.getInRangeColl() != 0) {
        setInRangeColl(other.getInRangeColl());
      }
      if (other.getInRangeAsc() != false) {
        setInRangeAsc(other.getInRangeAsc());
      }
      if (other.getInRangeNullsFirst() != false) {
        setInRangeNullsFirst(other.getInRangeNullsFirst());
      }
      if (other.getWinref() != 0) {
        setWinref(other.getWinref());
      }
      if (other.getCopiedOrder() != false) {
        setCopiedOrder(other.getCopiedOrder());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              refname_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (partitionClauseBuilder_ == null) {
                ensurePartitionClauseIsMutable();
                partitionClause_.add(m);
              } else {
                partitionClauseBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              com.premiumminds.sonar.postgres.protobuf.Node m =
                  input.readMessage(
                      com.premiumminds.sonar.postgres.protobuf.Node.parser(),
                      extensionRegistry);
              if (orderClauseBuilder_ == null) {
                ensureOrderClauseIsMutable();
                orderClause_.add(m);
              } else {
                orderClauseBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 40: {
              frameOptions_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getStartOffsetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getEndOffsetFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              startInRangeFunc_ = input.readUInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              endInRangeFunc_ = input.readUInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              inRangeColl_ = input.readUInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              inRangeAsc_ = input.readBool();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              inRangeNullsFirst_ = input.readBool();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              winref_ = input.readUInt32();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 112: {
              copiedOrder_ = input.readBool();
              bitField0_ |= 0x00002000;
              break;
            } // case 112
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object refname_ = "";
    /**
     * <code>string refname = 2 [json_name = "refname"];</code>
     * @return The refname.
     */
    public java.lang.String getRefname() {
      java.lang.Object ref = refname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string refname = 2 [json_name = "refname"];</code>
     * @return The bytes for refname.
     */
    public com.google.protobuf.ByteString
        getRefnameBytes() {
      java.lang.Object ref = refname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string refname = 2 [json_name = "refname"];</code>
     * @param value The refname to set.
     * @return This builder for chaining.
     */
    public Builder setRefname(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      refname_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string refname = 2 [json_name = "refname"];</code>
     * @return This builder for chaining.
     */
    public Builder clearRefname() {
      refname_ = getDefaultInstance().getRefname();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string refname = 2 [json_name = "refname"];</code>
     * @param value The bytes for refname to set.
     * @return This builder for chaining.
     */
    public Builder setRefnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      refname_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> partitionClause_ =
      java.util.Collections.emptyList();
    private void ensurePartitionClauseIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        partitionClause_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(partitionClause_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> partitionClauseBuilder_;

    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getPartitionClauseList() {
      if (partitionClauseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(partitionClause_);
      } else {
        return partitionClauseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public int getPartitionClauseCount() {
      if (partitionClauseBuilder_ == null) {
        return partitionClause_.size();
      } else {
        return partitionClauseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getPartitionClause(int index) {
      if (partitionClauseBuilder_ == null) {
        return partitionClause_.get(index);
      } else {
        return partitionClauseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder setPartitionClause(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (partitionClauseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionClauseIsMutable();
        partitionClause_.set(index, value);
        onChanged();
      } else {
        partitionClauseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder setPartitionClause(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (partitionClauseBuilder_ == null) {
        ensurePartitionClauseIsMutable();
        partitionClause_.set(index, builderForValue.build());
        onChanged();
      } else {
        partitionClauseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder addPartitionClause(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (partitionClauseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionClauseIsMutable();
        partitionClause_.add(value);
        onChanged();
      } else {
        partitionClauseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder addPartitionClause(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (partitionClauseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePartitionClauseIsMutable();
        partitionClause_.add(index, value);
        onChanged();
      } else {
        partitionClauseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder addPartitionClause(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (partitionClauseBuilder_ == null) {
        ensurePartitionClauseIsMutable();
        partitionClause_.add(builderForValue.build());
        onChanged();
      } else {
        partitionClauseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder addPartitionClause(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (partitionClauseBuilder_ == null) {
        ensurePartitionClauseIsMutable();
        partitionClause_.add(index, builderForValue.build());
        onChanged();
      } else {
        partitionClauseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder addAllPartitionClause(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (partitionClauseBuilder_ == null) {
        ensurePartitionClauseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, partitionClause_);
        onChanged();
      } else {
        partitionClauseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder clearPartitionClause() {
      if (partitionClauseBuilder_ == null) {
        partitionClause_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        partitionClauseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public Builder removePartitionClause(int index) {
      if (partitionClauseBuilder_ == null) {
        ensurePartitionClauseIsMutable();
        partitionClause_.remove(index);
        onChanged();
      } else {
        partitionClauseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getPartitionClauseBuilder(
        int index) {
      return getPartitionClauseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getPartitionClauseOrBuilder(
        int index) {
      if (partitionClauseBuilder_ == null) {
        return partitionClause_.get(index);  } else {
        return partitionClauseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getPartitionClauseOrBuilderList() {
      if (partitionClauseBuilder_ != null) {
        return partitionClauseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(partitionClause_);
      }
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addPartitionClauseBuilder() {
      return getPartitionClauseFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addPartitionClauseBuilder(
        int index) {
      return getPartitionClauseFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node partition_clause = 3 [json_name = "partitionClause"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getPartitionClauseBuilderList() {
      return getPartitionClauseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getPartitionClauseFieldBuilder() {
      if (partitionClauseBuilder_ == null) {
        partitionClauseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                partitionClause_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        partitionClause_ = null;
      }
      return partitionClauseBuilder_;
    }

    private java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> orderClause_ =
      java.util.Collections.emptyList();
    private void ensureOrderClauseIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        orderClause_ = new java.util.ArrayList<com.premiumminds.sonar.postgres.protobuf.Node>(orderClause_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> orderClauseBuilder_;

    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node> getOrderClauseList() {
      if (orderClauseBuilder_ == null) {
        return java.util.Collections.unmodifiableList(orderClause_);
      } else {
        return orderClauseBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public int getOrderClauseCount() {
      if (orderClauseBuilder_ == null) {
        return orderClause_.size();
      } else {
        return orderClauseBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getOrderClause(int index) {
      if (orderClauseBuilder_ == null) {
        return orderClause_.get(index);
      } else {
        return orderClauseBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder setOrderClause(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (orderClauseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderClauseIsMutable();
        orderClause_.set(index, value);
        onChanged();
      } else {
        orderClauseBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder setOrderClause(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (orderClauseBuilder_ == null) {
        ensureOrderClauseIsMutable();
        orderClause_.set(index, builderForValue.build());
        onChanged();
      } else {
        orderClauseBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder addOrderClause(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (orderClauseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderClauseIsMutable();
        orderClause_.add(value);
        onChanged();
      } else {
        orderClauseBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder addOrderClause(
        int index, com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (orderClauseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOrderClauseIsMutable();
        orderClause_.add(index, value);
        onChanged();
      } else {
        orderClauseBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder addOrderClause(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (orderClauseBuilder_ == null) {
        ensureOrderClauseIsMutable();
        orderClause_.add(builderForValue.build());
        onChanged();
      } else {
        orderClauseBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder addOrderClause(
        int index, com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (orderClauseBuilder_ == null) {
        ensureOrderClauseIsMutable();
        orderClause_.add(index, builderForValue.build());
        onChanged();
      } else {
        orderClauseBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder addAllOrderClause(
        java.lang.Iterable<? extends com.premiumminds.sonar.postgres.protobuf.Node> values) {
      if (orderClauseBuilder_ == null) {
        ensureOrderClauseIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, orderClause_);
        onChanged();
      } else {
        orderClauseBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder clearOrderClause() {
      if (orderClauseBuilder_ == null) {
        orderClause_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        orderClauseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public Builder removeOrderClause(int index) {
      if (orderClauseBuilder_ == null) {
        ensureOrderClauseIsMutable();
        orderClause_.remove(index);
        onChanged();
      } else {
        orderClauseBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getOrderClauseBuilder(
        int index) {
      return getOrderClauseFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getOrderClauseOrBuilder(
        int index) {
      if (orderClauseBuilder_ == null) {
        return orderClause_.get(index);  } else {
        return orderClauseBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public java.util.List<? extends com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
         getOrderClauseOrBuilderList() {
      if (orderClauseBuilder_ != null) {
        return orderClauseBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(orderClause_);
      }
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addOrderClauseBuilder() {
      return getOrderClauseFieldBuilder().addBuilder(
          com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder addOrderClauseBuilder(
        int index) {
      return getOrderClauseFieldBuilder().addBuilder(
          index, com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance());
    }
    /**
     * <code>repeated .pg_query.Node order_clause = 4 [json_name = "orderClause"];</code>
     */
    public java.util.List<com.premiumminds.sonar.postgres.protobuf.Node.Builder> 
         getOrderClauseBuilderList() {
      return getOrderClauseFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getOrderClauseFieldBuilder() {
      if (orderClauseBuilder_ == null) {
        orderClauseBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                orderClause_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        orderClause_ = null;
      }
      return orderClauseBuilder_;
    }

    private int frameOptions_ ;
    /**
     * <code>int32 frame_options = 5 [json_name = "frameOptions"];</code>
     * @return The frameOptions.
     */
    @java.lang.Override
    public int getFrameOptions() {
      return frameOptions_;
    }
    /**
     * <code>int32 frame_options = 5 [json_name = "frameOptions"];</code>
     * @param value The frameOptions to set.
     * @return This builder for chaining.
     */
    public Builder setFrameOptions(int value) {

      frameOptions_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 frame_options = 5 [json_name = "frameOptions"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFrameOptions() {
      bitField0_ = (bitField0_ & ~0x00000010);
      frameOptions_ = 0;
      onChanged();
      return this;
    }

    private com.premiumminds.sonar.postgres.protobuf.Node startOffset_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> startOffsetBuilder_;
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     * @return Whether the startOffset field is set.
     */
    public boolean hasStartOffset() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     * @return The startOffset.
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getStartOffset() {
      if (startOffsetBuilder_ == null) {
        return startOffset_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : startOffset_;
      } else {
        return startOffsetBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     */
    public Builder setStartOffset(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (startOffsetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        startOffset_ = value;
      } else {
        startOffsetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     */
    public Builder setStartOffset(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (startOffsetBuilder_ == null) {
        startOffset_ = builderForValue.build();
      } else {
        startOffsetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     */
    public Builder mergeStartOffset(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (startOffsetBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          startOffset_ != null &&
          startOffset_ != com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance()) {
          getStartOffsetBuilder().mergeFrom(value);
        } else {
          startOffset_ = value;
        }
      } else {
        startOffsetBuilder_.mergeFrom(value);
      }
      if (startOffset_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     */
    public Builder clearStartOffset() {
      bitField0_ = (bitField0_ & ~0x00000020);
      startOffset_ = null;
      if (startOffsetBuilder_ != null) {
        startOffsetBuilder_.dispose();
        startOffsetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getStartOffsetBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getStartOffsetFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getStartOffsetOrBuilder() {
      if (startOffsetBuilder_ != null) {
        return startOffsetBuilder_.getMessageOrBuilder();
      } else {
        return startOffset_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : startOffset_;
      }
    }
    /**
     * <code>.pg_query.Node start_offset = 6 [json_name = "startOffset"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getStartOffsetFieldBuilder() {
      if (startOffsetBuilder_ == null) {
        startOffsetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                getStartOffset(),
                getParentForChildren(),
                isClean());
        startOffset_ = null;
      }
      return startOffsetBuilder_;
    }

    private com.premiumminds.sonar.postgres.protobuf.Node endOffset_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> endOffsetBuilder_;
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     * @return Whether the endOffset field is set.
     */
    public boolean hasEndOffset() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     * @return The endOffset.
     */
    public com.premiumminds.sonar.postgres.protobuf.Node getEndOffset() {
      if (endOffsetBuilder_ == null) {
        return endOffset_ == null ? com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : endOffset_;
      } else {
        return endOffsetBuilder_.getMessage();
      }
    }
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     */
    public Builder setEndOffset(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (endOffsetBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        endOffset_ = value;
      } else {
        endOffsetBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     */
    public Builder setEndOffset(
        com.premiumminds.sonar.postgres.protobuf.Node.Builder builderForValue) {
      if (endOffsetBuilder_ == null) {
        endOffset_ = builderForValue.build();
      } else {
        endOffsetBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     */
    public Builder mergeEndOffset(com.premiumminds.sonar.postgres.protobuf.Node value) {
      if (endOffsetBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          endOffset_ != null &&
          endOffset_ != com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance()) {
          getEndOffsetBuilder().mergeFrom(value);
        } else {
          endOffset_ = value;
        }
      } else {
        endOffsetBuilder_.mergeFrom(value);
      }
      if (endOffset_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     */
    public Builder clearEndOffset() {
      bitField0_ = (bitField0_ & ~0x00000040);
      endOffset_ = null;
      if (endOffsetBuilder_ != null) {
        endOffsetBuilder_.dispose();
        endOffsetBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.Node.Builder getEndOffsetBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getEndOffsetFieldBuilder().getBuilder();
    }
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     */
    public com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder getEndOffsetOrBuilder() {
      if (endOffsetBuilder_ != null) {
        return endOffsetBuilder_.getMessageOrBuilder();
      } else {
        return endOffset_ == null ?
            com.premiumminds.sonar.postgres.protobuf.Node.getDefaultInstance() : endOffset_;
      }
    }
    /**
     * <code>.pg_query.Node end_offset = 7 [json_name = "endOffset"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder> 
        getEndOffsetFieldBuilder() {
      if (endOffsetBuilder_ == null) {
        endOffsetBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.premiumminds.sonar.postgres.protobuf.Node, com.premiumminds.sonar.postgres.protobuf.Node.Builder, com.premiumminds.sonar.postgres.protobuf.NodeOrBuilder>(
                getEndOffset(),
                getParentForChildren(),
                isClean());
        endOffset_ = null;
      }
      return endOffsetBuilder_;
    }

    private int startInRangeFunc_ ;
    /**
     * <code>uint32 start_in_range_func = 8 [json_name = "startInRangeFunc"];</code>
     * @return The startInRangeFunc.
     */
    @java.lang.Override
    public int getStartInRangeFunc() {
      return startInRangeFunc_;
    }
    /**
     * <code>uint32 start_in_range_func = 8 [json_name = "startInRangeFunc"];</code>
     * @param value The startInRangeFunc to set.
     * @return This builder for chaining.
     */
    public Builder setStartInRangeFunc(int value) {

      startInRangeFunc_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 start_in_range_func = 8 [json_name = "startInRangeFunc"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStartInRangeFunc() {
      bitField0_ = (bitField0_ & ~0x00000080);
      startInRangeFunc_ = 0;
      onChanged();
      return this;
    }

    private int endInRangeFunc_ ;
    /**
     * <code>uint32 end_in_range_func = 9 [json_name = "endInRangeFunc"];</code>
     * @return The endInRangeFunc.
     */
    @java.lang.Override
    public int getEndInRangeFunc() {
      return endInRangeFunc_;
    }
    /**
     * <code>uint32 end_in_range_func = 9 [json_name = "endInRangeFunc"];</code>
     * @param value The endInRangeFunc to set.
     * @return This builder for chaining.
     */
    public Builder setEndInRangeFunc(int value) {

      endInRangeFunc_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 end_in_range_func = 9 [json_name = "endInRangeFunc"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEndInRangeFunc() {
      bitField0_ = (bitField0_ & ~0x00000100);
      endInRangeFunc_ = 0;
      onChanged();
      return this;
    }

    private int inRangeColl_ ;
    /**
     * <code>uint32 in_range_coll = 10 [json_name = "inRangeColl"];</code>
     * @return The inRangeColl.
     */
    @java.lang.Override
    public int getInRangeColl() {
      return inRangeColl_;
    }
    /**
     * <code>uint32 in_range_coll = 10 [json_name = "inRangeColl"];</code>
     * @param value The inRangeColl to set.
     * @return This builder for chaining.
     */
    public Builder setInRangeColl(int value) {

      inRangeColl_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 in_range_coll = 10 [json_name = "inRangeColl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInRangeColl() {
      bitField0_ = (bitField0_ & ~0x00000200);
      inRangeColl_ = 0;
      onChanged();
      return this;
    }

    private boolean inRangeAsc_ ;
    /**
     * <code>bool in_range_asc = 11 [json_name = "inRangeAsc"];</code>
     * @return The inRangeAsc.
     */
    @java.lang.Override
    public boolean getInRangeAsc() {
      return inRangeAsc_;
    }
    /**
     * <code>bool in_range_asc = 11 [json_name = "inRangeAsc"];</code>
     * @param value The inRangeAsc to set.
     * @return This builder for chaining.
     */
    public Builder setInRangeAsc(boolean value) {

      inRangeAsc_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>bool in_range_asc = 11 [json_name = "inRangeAsc"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInRangeAsc() {
      bitField0_ = (bitField0_ & ~0x00000400);
      inRangeAsc_ = false;
      onChanged();
      return this;
    }

    private boolean inRangeNullsFirst_ ;
    /**
     * <code>bool in_range_nulls_first = 12 [json_name = "inRangeNullsFirst"];</code>
     * @return The inRangeNullsFirst.
     */
    @java.lang.Override
    public boolean getInRangeNullsFirst() {
      return inRangeNullsFirst_;
    }
    /**
     * <code>bool in_range_nulls_first = 12 [json_name = "inRangeNullsFirst"];</code>
     * @param value The inRangeNullsFirst to set.
     * @return This builder for chaining.
     */
    public Builder setInRangeNullsFirst(boolean value) {

      inRangeNullsFirst_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>bool in_range_nulls_first = 12 [json_name = "inRangeNullsFirst"];</code>
     * @return This builder for chaining.
     */
    public Builder clearInRangeNullsFirst() {
      bitField0_ = (bitField0_ & ~0x00000800);
      inRangeNullsFirst_ = false;
      onChanged();
      return this;
    }

    private int winref_ ;
    /**
     * <code>uint32 winref = 13 [json_name = "winref"];</code>
     * @return The winref.
     */
    @java.lang.Override
    public int getWinref() {
      return winref_;
    }
    /**
     * <code>uint32 winref = 13 [json_name = "winref"];</code>
     * @param value The winref to set.
     * @return This builder for chaining.
     */
    public Builder setWinref(int value) {

      winref_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 winref = 13 [json_name = "winref"];</code>
     * @return This builder for chaining.
     */
    public Builder clearWinref() {
      bitField0_ = (bitField0_ & ~0x00001000);
      winref_ = 0;
      onChanged();
      return this;
    }

    private boolean copiedOrder_ ;
    /**
     * <code>bool copied_order = 14 [json_name = "copiedOrder"];</code>
     * @return The copiedOrder.
     */
    @java.lang.Override
    public boolean getCopiedOrder() {
      return copiedOrder_;
    }
    /**
     * <code>bool copied_order = 14 [json_name = "copiedOrder"];</code>
     * @param value The copiedOrder to set.
     * @return This builder for chaining.
     */
    public Builder setCopiedOrder(boolean value) {

      copiedOrder_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>bool copied_order = 14 [json_name = "copiedOrder"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCopiedOrder() {
      bitField0_ = (bitField0_ & ~0x00002000);
      copiedOrder_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:pg_query.WindowClause)
  }

  // @@protoc_insertion_point(class_scope:pg_query.WindowClause)
  private static final com.premiumminds.sonar.postgres.protobuf.WindowClause DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.premiumminds.sonar.postgres.protobuf.WindowClause();
  }

  public static com.premiumminds.sonar.postgres.protobuf.WindowClause getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WindowClause>
      PARSER = new com.google.protobuf.AbstractParser<WindowClause>() {
    @java.lang.Override
    public WindowClause parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WindowClause> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WindowClause> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.premiumminds.sonar.postgres.protobuf.WindowClause getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

