// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pg_query.proto

package com.premiumminds.sonar.plpgsql.protobuf;

public interface LoadStmtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:pg_query.LoadStmt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filename = 1 [json_name = "filename"];</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 1 [json_name = "filename"];</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();
}
